using Scrapyard.Core;

namespace Scrapyard.Meta;

/// <summary>
/// Every lock in the game, in the one condition language.
/// </summary>
/// <remarks>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c>. A lock retyped wrong is either a chassis nobody can
/// earn or one everybody gets for free, and neither announces itself - so these are emitted from
/// the catalogs that own them rather than copied.
/// </para>
/// <para>
/// <b>THE CRITERIA ARE PUBLISHED NOWHERE.</b> A locked chassis is a silhouette and a question mark.
/// These conditions exist to be EVALUATED, and the only place one is ever stated to a player is the
/// achievement that fires on earning it, in the past tense. There is deliberately no imperative
/// description here and there must not be one.
/// </para>
/// <para>
/// <b><c>Never</c> means the criteria have not been written.</b> Four chassis carry it. It is not a
/// placeholder to be filled in with something plausible: a guessed number is a design decision made
/// by accident, and once shipped it is something players have already played around.
/// </para>
/// </remarks>
/// <param name="Id">What a save records, and what a condition names.</param>
/// <param name="Name">What the pick screen calls it.</param>
/// <param name="Cond">What has to have happened for it to be pickable.</param>
/// <param name="Line">
/// The one line under the name: a chassis's identity, a yard's blurb. It is the only thing either
/// pick screen says about what is being chosen.
/// </param>
/// <param name="Playable">
/// Whether the CONTENT exists, which is a different question from whether this save has earned it.
/// A level can be unfinished, or finished and unearned, or open - and a screen that told a player to
/// go and win something not built yet would be worse than one that said nothing.
/// </param>
/// <param name="Art">
/// The sprite the pick screen shows. NAMED HERE rather than derived from the index, because the
/// index is a fact about a catalog's current order and the art is a fact about the thing.
/// </param>
public readonly record struct LockedThing(
    string Id, string Name, UnlockCond Cond, string Line, bool Playable, string Art);

/// <summary>A card lock, which also carries the catalog index the deck is keyed by.</summary>
public readonly record struct LockedCard(int Index, string Id, string Name, UnlockCond Cond);

/// <summary>
/// Every upgrade id the save may legitimately hold, so a stored one can be resolved.
/// </summary>
/// <remarks>
/// <para>
/// HERE RATHER THAN IN THE DRAWING LAYER, because the save is filtered on load and
/// <see cref="Settings.Reconcile"/> lives in this project. <c>CardTexts</c> in
/// <c>Scrapyard.Game</c> carries the same ids for the screens; both are generated from the same
/// catalog line, so the two cannot drift.
/// </para>
/// <para>
/// <c>Ascended</c> NAMES PARENT IDS AND NOTHING ELSE - not how many there are, not what they
/// become. It exists so a <c>HeldAscensions</c> entry whose tier 8 has since been withdrawn is
/// dropped rather than left claiming a page nothing can draw, which is the same rule every other
/// list follows.
/// </para>
/// </remarks>
public static class CardIds
{
    public static readonly string[] All =
    {
        "w-cannon",
        "w-missile-short",
        "w-missile-long",
        "w-machine-gun",
        "w-flak-cannon",
        "w-artillery",
        "w-drone",
        "w-phase-cannon",
        "w-laser-short",
        "w-laser-medium",
        "w-laser-long",
        "p-range",
        "p-damage",
        "p-rate",
        "p-speed",
        "p-armour",
        "p-repair",
        "p-shield",
        "p-radiator",
        "p-blast",
        "p-ammo",
        "w-mortar",
        "w-plasma",
        "w-sludge",
    };

    /// <summary>The cards that HAVE a tier 8, by their own id.</summary>
    public static readonly string[] Ascended =
    {
        "w-cannon",
        "w-missile-long",
        "w-laser-short",
        "w-laser-medium",
        "w-laser-long",
    };
}

public sealed class HeroUnlocks
{
    public static readonly LockedThing[] Heroes =
    {
        new("slate", "Slate", UnlockCond.Always(), "Light biped, twin gun pods. Opens with the Medium Laser, and vents its heat 50% faster.", true, "mech_slate"),
        new("moss", "Moss", UnlockCond.Wave(3), "Light strider, rotary drums. Opens with the Short Laser at double reach.", true, "mech_moss"),
        new("ember", "Ember", UnlockCond.BossKillHolding(WeaponIds.LaserLong), "Light strider, one heavy cannon. Opens with the Long Laser, 30% hotter-hitting.", true, "mech_ember"),
        new("amber", "Amber", UnlockCond.DiedTo("boss"), "Heavy biped, one heavy cannon. Opens with the Cannon, and its shells punch through.", true, "mech_amber"),
        new("onyx", "Onyx", UnlockCond.KillsWith(100, WeaponIds.MissileShort, WeaponIds.MissileLong), "Heavy quad, boxed missile racks. Opens with the Long Missiles, and fires one more.", true, "mech_onyx"),
        new("ash", "Ash", UnlockCond.BossKillBy(WeaponIds.MissileShort, WeaponIds.MissileLong), "Light biped, boxed missile racks. Opens with the Short Missiles, rearmed 20% faster.", true, "mech_ash"),
        new("bone", "Bone", UnlockCond.ContactHits(20), "Light strider, twin gun pods. Opens with the Machine Gun, 30% harder-hitting.", true, "mech_bone"),
        new("plum", "Plum", UnlockCond.Tier(17, 7), "Heavy biped, no gun at all. Nothing but an Energy Shield, recharging 60% faster. Kill with it.", true, "mech_plum"),
        new("fern", "Fern", UnlockCond.WinLevel("scrapyard"), "Light hover, forward claw arms. Opens with Drones, and builds them 10% faster.", true, "mech_fern"),
        new("indigo", "Indigo", UnlockCond.KillsWithTotal(999, WeaponIds.Artillery), "Heavy strider, spine-slung artillery tube. Opens with the Heavy Artillery, blasting 15% wider.", true, "mech_indigo"),
        new("brass", "Brass", UnlockCond.WinLevel("mossy-mayhem"), "Light hover, one heavy tube. Opens with the Phase Cannon, 10% harder-hitting.", true, "mech_brass"),
        new("vermilion", "Vermilion", UnlockCond.ChassisOwned(6), "Light hover, rotary drums. Opens with the Flak Cannon, and throws an extra shell every burst.", true, "mech_vermilion"),
        new("jade", "Jade", UnlockCond.Always(), "Heavy biped, forward claw arms. Opens with Toxic Sludge, laying pools 20% wider.", true, "mech_jade"),
        new("rust", "Rust", UnlockCond.Always(), "Heavy quad, spine-slung artillery tube. Opens with the Mortar, lobbing 30% harder.", true, "mech_rust"),
        new("cobalt", "Cobalt", UnlockCond.Never(), "Heavy quad, twin gun pods. Opens with the Medium Laser.", true, "mech_cobalt"),
        new("copper", "Copper", UnlockCond.Always(), "Heavy quad, rotary drums. Opens with the Plasma Thrower, throwing 10% further and 10% hotter.", true, "mech_copper"),
    };

    public static readonly LockedThing[] Levels =
    {
        new("scrapyard", "Scrapyard", UnlockCond.Always(), "A fenced yard of rust and wrecks. 16 minutes, 8 bosses, then the last Scraplord.", true, "scrap_0"),
        new("mossy-mayhem", "Mossy Mayhem", UnlockCond.WinLevel("scrapyard"), "Open moss and turf, running out further than you can walk. No fence, no corners.", true, "level_mossy"),
        new("city-chaos", "City Chaos", UnlockCond.WinLevel("mossy-mayhem"), "Streets on a grid, blocks to fight around, and the machines that own them now.", true, "level_city"),
    };

    /// <summary>The cards that must be EARNED. Everything not listed is offerable from the start.</summary>
    public static readonly LockedCard[] Cards =
    {
        new(4, "w-flak-cannon", "Flak Cannon", UnlockCond.KillsWithTotal(9001, WeaponIds.FlakCannon)),
        new(6, "w-drone", "Drones", UnlockCond.KillsWithTotal(1984, WeaponIds.Drone)),
        new(7, "w-phase-cannon", "Phase Cannon", UnlockCond.KillsWithTotal(1001, WeaponIds.PhaseCannon)),
        new(16, "p-repair", "Field Repair", UnlockCond.FullRepair()),
        new(18, "p-radiator", "Radiator Bank", UnlockCond.LasersOverheated()),
        new(19, "p-blast", "Shaped Charges", UnlockCond.SplashKillsTotal(2000)),
        new(20, "p-ammo", "Ammo Drums", UnlockCond.ReloadsTotal(1911)),
        new(21, "w-mortar", "Mortar", UnlockCond.KillsWithTotal(1812, WeaponIds.Mortar)),
        new(22, "w-plasma", "Plasma Thrower", UnlockCond.BurningAtOnce(30)),
        new(23, "w-sludge", "Toxic Sludge", UnlockCond.EliteKillsWithTotal(30, WeaponIds.Sludge)),
    };

    /// <summary>
    /// Which chassis this run has just earned, by catalog index.
    /// </summary>
    /// <remarks>
    /// A SET UNION: anything the save already owns is skipped, so this reports each unlock exactly
    /// once however often it is called. That is what makes banking once a second free.
    /// </remarks>
    public IEnumerable<int> NewlyUnlocked(Settings save, RunRecord run, CareerRecord career)
    {
        for (int i = 0; i < Heroes.Length; i++)
        {
            var h = Heroes[i];
            if (save.UnlockedHeroes.Contains(h.Id)) continue;
            if (!Unlocks.Meets(h.Cond, run, career)) continue;
            yield return i;
        }
    }

    public IEnumerable<string> NewlyUnlockedLevels(Settings save, RunRecord run, CareerRecord career)
    {
        foreach (var l in Levels)
        {
            if (save.UnlockedLevels.Contains(l.Id)) continue;
            if (!Unlocks.Meets(l.Cond, run, career)) continue;
            yield return l.Id;
        }
    }

    public IEnumerable<LockedCard> NewlyEarnedCards(Settings save, RunRecord run, CareerRecord career)
    {
        foreach (var c in Cards)
        {
            if (save.EarnedCards.Contains(c.Id)) continue;
            if (!Unlocks.Meets(c.Cond, run, career)) continue;
            yield return c;
        }
    }

    public static void Verify(int heroCount)
    {
        if (Heroes.Length != heroCount)
        {
            throw new InvalidOperationException(
                $"HeroUnlocks holds {Heroes.Length} chassis but the catalog has {heroCount}. " +
                "Re-run: npx tsx tools/gen_ui_text.ts");
        }
    }
}
