using Scrapyard.Core;

namespace Scrapyard.Meta;

/// <summary>
/// Every lock in the game, in the one condition language.
/// </summary>
/// <remarks>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c>. A lock retyped wrong is either a chassis nobody can
/// earn or one everybody gets for free, and neither announces itself - so these are emitted from
/// the catalogs that own them rather than copied.
/// </para>
/// <para>
/// <b>THE CRITERIA ARE PUBLISHED NOWHERE.</b> A locked chassis is a silhouette and a question mark.
/// These conditions exist to be EVALUATED, and the only place one is ever stated to a player is the
/// achievement that fires on earning it, in the past tense. There is deliberately no imperative
/// description here and there must not be one.
/// </para>
/// <para>
/// <b><c>Never</c> means the criteria have not been written.</b> Four chassis carry it. It is not a
/// placeholder to be filled in with something plausible: a guessed number is a design decision made
/// by accident, and once shipped it is something players have already played around.
/// </para>
/// </remarks>
public readonly record struct LockedThing(string Id, string Name, UnlockCond Cond);

/// <summary>A card lock, which also carries the catalog index the deck is keyed by.</summary>
public readonly record struct LockedCard(int Index, string Id, string Name, UnlockCond Cond);

public sealed class HeroUnlocks
{
    public static readonly LockedThing[] Heroes =
    {
        new("slate", "Slate", UnlockCond.Always()),
        new("moss", "Moss", UnlockCond.Wave(3)),
        new("ember", "Ember", UnlockCond.BossKillHolding(WeaponIds.LaserLong)),
        new("amber", "Amber", UnlockCond.DiedTo("boss")),
        new("onyx", "Onyx", UnlockCond.KillsWith(100, WeaponIds.MissileShort, WeaponIds.MissileLong)),
        new("ash", "Ash", UnlockCond.BossKillBy(WeaponIds.MissileShort, WeaponIds.MissileLong)),
        new("bone", "Bone", UnlockCond.ContactHits(20)),
        new("plum", "Plum", UnlockCond.Tier(17, 7)),
        new("fern", "Fern", UnlockCond.WinLevel("scrapyard")),
        new("indigo", "Indigo", UnlockCond.KillsWithTotal(999, WeaponIds.Artillery)),
        new("brass", "Brass", UnlockCond.WinLevel("mossy-mayhem")),
        new("vermilion", "Vermilion", UnlockCond.ChassisOwned(6)),
        new("jade", "Jade", UnlockCond.Never()),
        new("rust", "Rust", UnlockCond.Never()),
        new("cobalt", "Cobalt", UnlockCond.Never()),
        new("copper", "Copper", UnlockCond.Never()),
    };

    public static readonly LockedThing[] Levels =
    {
        new("scrapyard", "Scrapyard", UnlockCond.Always()),
        new("mossy-mayhem", "Mossy Mayhem", UnlockCond.WinLevel("scrapyard")),
        new("city-chaos", "City Chaos", UnlockCond.WinLevel("mossy-mayhem")),
    };

    /// <summary>The cards that must be EARNED. Everything not listed is offerable from the start.</summary>
    public static readonly LockedCard[] Cards =
    {
        new(4, "w-flak-cannon", "Flak Cannon", UnlockCond.KillsWithTotal(9001, WeaponIds.FlakCannon)),
        new(6, "w-drone", "Drones", UnlockCond.KillsWithTotal(1984, WeaponIds.Drone)),
        new(7, "w-phase-cannon", "Phase Cannon", UnlockCond.KillsWithTotal(1001, WeaponIds.PhaseCannon)),
        new(16, "p-repair", "Field Repair", UnlockCond.FullRepair()),
        new(18, "p-radiator", "Radiator Bank", UnlockCond.LasersOverheated()),
        new(19, "p-blast", "Shaped Charges", UnlockCond.SplashKillsTotal(2000)),
        new(20, "p-ammo", "Ammo Drums", UnlockCond.ReloadsTotal(1911)),
    };

    /// <summary>
    /// Which chassis this run has just earned, by catalog index.
    /// </summary>
    /// <remarks>
    /// A SET UNION: anything the save already owns is skipped, so this reports each unlock exactly
    /// once however often it is called. That is what makes banking once a second free.
    /// </remarks>
    public IEnumerable<int> NewlyUnlocked(Settings save, RunRecord run, CareerRecord career)
    {
        for (int i = 0; i < Heroes.Length; i++)
        {
            var h = Heroes[i];
            if (save.UnlockedHeroes.Contains(h.Id)) continue;
            if (!Unlocks.Meets(h.Cond, run, career)) continue;
            yield return i;
        }
    }

    public IEnumerable<string> NewlyUnlockedLevels(Settings save, RunRecord run, CareerRecord career)
    {
        foreach (var l in Levels)
        {
            if (save.UnlockedLevels.Contains(l.Id)) continue;
            if (!Unlocks.Meets(l.Cond, run, career)) continue;
            yield return l.Id;
        }
    }

    public IEnumerable<LockedCard> NewlyEarnedCards(Settings save, RunRecord run, CareerRecord career)
    {
        foreach (var c in Cards)
        {
            if (save.EarnedCards.Contains(c.Id)) continue;
            if (!Unlocks.Meets(c.Cond, run, career)) continue;
            yield return c;
        }
    }

    public static void Verify(int heroCount)
    {
        if (Heroes.Length != heroCount)
        {
            throw new InvalidOperationException(
                $"HeroUnlocks holds {Heroes.Length} chassis but the catalog has {heroCount}. " +
                "Re-run: npx tsx tools/gen_ui_text.ts");
        }
    }
}
