namespace Scrapyard.Meta;

/// <summary>
/// What a workshop upgrade SAYS and what it COSTS.
/// </summary>
/// <remarks>
/// <para>
/// NOT IN <c>Scrapyard.Core</c>. The simulation reads a workshop upgrade's EFFECTS and its tier
/// count and nothing else - the name, the blurb, the price and the version are shop economics, and
/// a run that has already started cannot be changed by any of them.
/// </para>
/// <para>
/// <c>Version</c> IS LOAD-BEARING. A save records the version a purchase was made under; when the
/// upgrade's effect later changes, the version bumps and <see cref="Settings"/> REFUNDS the
/// purchase rather than silently handing the player something they did not buy. That is why the
/// number is generated from the catalog rather than assumed to be 1.
/// </para>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c>. THE ORDER IS THE FORMAT: index i here is
/// <c>MetaCatalog.All</c> index i, which is also what <c>World.Meta.Tiers</c> is keyed by.
/// </para>
/// </remarks>
public readonly record struct WorkshopEntry(
    string Id, string Name, string Blurb, int Tiers, int Cost, int Version);

public static class WorkshopText
{
    public static readonly WorkshopEntry[] All =
    {
        new("m-passives", "Auxiliary Bay", "The chassis carries another passive mount. Every run, whichever mech you take out.", 2, 400, 1),
        new("m-mounts", "Reinforced Mounts", "The chassis carries another gun mount. Every run, whichever mech you take out.", 2, 200, 2),
        new("m-damage", "Ordnance Stores", "Every gun the yard hands you hits harder, from the first second of the run. A hotter-running laser burns through its heat faster.", 7, 50, 1),
        new("m-blast", "Bursting Charges", "Everything that explodes, explodes wider - the artillery barrage and a spent drone alike.", 3, 70, 1),
        new("m-range", "Optical Array", "Everything reaches further, so the horde is dying before it arrives.", 5, 30, 1),
        new("m-speed", "Servo Tuning", "The chassis walks quicker, whichever chassis it is.", 3, 45, 1),
        new("m-rate", "Autoloaders", "Shorter gaps between shots on everything that has a gap.", 3, 40, 1),
        new("m-magnet", "Scrap Magnetics", "Cores come to you from further off, so the ground you cannot safely cross still pays.", 3, 35, 1),
        new("m-hp", "Hull Reserves", "The chassis carries more hull to start with. Nothing about it stops the horde reaching you - it just takes more to end the run.", 4, 40, 1),
        new("m-armour", "Hull Plating", "Takes a little off every hit you take, for the whole run.", 2, 50, 1),
        new("m-insurance", "Mech Insurance", "The first hit that would end a run does not. The hull comes back whole and nothing can touch you for a few seconds while you get clear.", 1, 100, 1),
        new("m-drone", "Fabricator Feed", "The drone bay turns a new drone around sooner.", 2, 80, 1),
        new("m-laser", "Coolant Baffles", "The beams shed heat faster, so they cut out for less of the fight.", 1, 100, 1),
        new("m-heatcap", "Heat Sinks", "Every beam runs a bigger heat buffer before it has to cut out.", 1, 80, 1),
        new("m-rerolls", "Rerolls", "Walk into every run holding more second opinions. A reroll deals a fresh three cards and still owes you the pick.", 3, 30, 1),
        new("m-repair", "Repair Bay", "A small repair clock, running from the first second of the run - a trickle next to Field Repair, and no substitute for finding it, but it never has to be found at all.", 3, 30, 1),
    };

    public static WorkshopEntry At(int index) =>
        index >= 0 && index < All.Length ? All[index] : new WorkshopEntry("", "?", "", 0, 0, 0);

    /// <summary>Throws if this table and the ported catalog have drifted apart.</summary>
    public static void Verify(int catalogCount)
    {
        if (All.Length != catalogCount)
        {
            throw new InvalidOperationException(
                $"WorkshopText holds {All.Length} entries but the catalog has {catalogCount}. " +
                "Re-run: npx tsx tools/gen_ui_text.ts");
        }
    }
}
