using Scrapyard.Core;

namespace Scrapyard.Meta;

/// <summary>
/// What a workshop upgrade SAYS and what it COSTS.
/// </summary>
/// <remarks>
/// <para>
/// NOT IN <c>Scrapyard.Core</c>. The simulation reads a workshop upgrade's EFFECTS and its tier
/// count and nothing else - the name, the blurb, the price and the version are shop economics, and
/// a run that has already started cannot be changed by any of them.
/// </para>
/// <para>
/// <c>Version</c> IS LOAD-BEARING. A save records the version a purchase was made under; when the
/// upgrade's effect later changes, the version bumps and <see cref="Settings"/> REFUNDS the
/// purchase rather than silently handing the player something they did not buy. That is why the
/// number is generated from the catalog rather than assumed to be 1.
/// </para>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c>. THE ORDER IS THE FORMAT: index i here is
/// <c>MetaCatalog.All</c> index i, which is also what <c>World.Meta.Tiers</c> is keyed by.
/// </para>
/// </remarks>
/// <param name="Id">The upgrade's id on disk, which is what a save records.</param>
/// <param name="Name">What the row is called.</param>
/// <param name="Blurb">One or two sentences on what buying it does to a run.</param>
/// <param name="Tiers">How many times it can be bought.</param>
/// <param name="Cost">The price of one tier. Flat: the seventh costs what the first did.</param>
/// <param name="Version">
/// Bumped when the upgrade's effect changes, so a save holding the old one is refunded rather than
/// silently handed something else.
/// </param>
/// <param name="Summary">
/// What the row says the mech HAS, indexed by tiers held. Index 0 is empty - a row with nothing
/// bought has no current effect to state, and shows <paramref name="Promise"/> instead.
/// </param>
/// <param name="Promise">The full effect, worded for a row that owns none of it.</param>
/// <param name="FullBare">
/// The full effect with its noun stripped, for the "+30% at full" tail on a part-bought row.
/// </param>
public readonly record struct WorkshopEntry(
    string Id, string Name, string Blurb, int Tiers, int Cost, int Version,
    string[] Summary, string Promise, string FullBare)
{
    /// <summary>What this row says about a mech holding <paramref name="tiers"/> of it.</summary>
    /// <remarks>
    /// CLAMPED rather than trusted. A save can hold more tiers than the catalog now offers - the
    /// ceiling came down between versions - and the shop still has to draw that row today. The
    /// refund path deals with the overpayment; this only has to say something true.
    /// </remarks>
    public string SummaryAt(int tiers)
    {
        if (Summary.Length == 0) return "";
        int t = tiers < 0 ? 0 : tiers;
        return Summary[t >= Summary.Length ? Summary.Length - 1 : t];
    }
}

public static class WorkshopText
{
    public static readonly WorkshopEntry[] All =
    {
        new("m-passives", "Auxiliary Bay", "The chassis carries another passive mount. Every run, whichever mech you take out.", 2, 400, 1,
            new[] { "", "1 extra passive slot", "2 extra passive slots" },
            "2 extra passive slots at full", "2"),
        new("m-mounts", "Reinforced Mounts", "The chassis carries another gun mount. Every run, whichever mech you take out.", 2, 200, 2,
            new[] { "", "1 extra mount", "2 extra mounts" },
            "2 extra mounts at full", "2"),
        new("m-damage", "Ordnance Stores", "Every gun the yard hands you hits harder, from the first second of the run. A hotter-running laser burns through its heat faster.", 7, 50, 1,
            new[] { "", "+4.3% damage", "+8.6% damage", "+12.9% damage", "+17.1% damage", "+21.4% damage", "+25.7% damage", "+30% damage" },
            "+30% damage at full", "+30%"),
        new("m-blast", "Bursting Charges", "Everything that explodes, explodes wider - the artillery barrage and a spent drone alike.", 3, 70, 1,
            new[] { "", "+10% blast radius", "+20% blast radius", "+30% blast radius" },
            "+30% blast radius at full", "+30%"),
        new("m-range", "Optical Array", "Everything reaches further, so the horde is dying before it arrives.", 5, 30, 1,
            new[] { "", "+3% range", "+6% range", "+9% range", "+12% range", "+15% range" },
            "+15% range at full", "+15%"),
        new("m-speed", "Servo Tuning", "The chassis walks quicker, whichever chassis it is.", 3, 45, 1,
            new[] { "", "+5% movement speed", "+10% movement speed", "+15% movement speed" },
            "+15% movement speed at full", "+15%"),
        new("m-rate", "Autoloaders", "Shorter gaps between shots on everything that has a gap.", 3, 40, 1,
            new[] { "", "+3.3% rate of fire", "+6.7% rate of fire", "+10% rate of fire" },
            "+10% rate of fire at full", "+10%"),
        new("m-magnet", "Scrap Magnetics", "Cores come to you from further off, so the ground you cannot safely cross still pays.", 3, 35, 1,
            new[] { "", "+15% pickup range", "+30% pickup range", "+45% pickup range" },
            "+45% pickup range at full", "+45%"),
        new("m-hp", "Hull Reserves", "The chassis carries more hull to start with. Nothing about it stops the horde reaching you - it just takes more to end the run.", 4, 40, 1,
            new[] { "", "5 max hull", "10 max hull", "15 max hull", "20 max hull" },
            "20 max hull at full", "20"),
        new("m-armour", "Hull Plating", "Takes a little off every hit you take, for the whole run.", 2, 50, 1,
            new[] { "", "1 armour", "2 armour" },
            "2 armour at full", "2"),
        new("m-insurance", "Mech Insurance", "The first hit that would end a run does not. The hull comes back whole and nothing can touch you for a few seconds while you get clear.", 1, 100, 1,
            new[] { "", "Survives your first death" },
            "Survives your first death", "Survives your first death"),
        new("m-drone", "Fabricator Feed", "The drone bay turns a new drone around sooner.", 2, 80, 1,
            new[] { "", "Drones build 1s faster", "Drones build 2s faster" },
            "Drones build 2s faster at full", "2s"),
        new("m-laser", "Coolant Baffles", "The beams shed heat faster, so they cut out for less of the fight.", 1, 100, 1,
            new[] { "", "+10% heat dispersion" },
            "+10% heat dispersion", "+10%"),
        new("m-heatcap", "Heat Sinks", "Every beam runs a bigger heat buffer before it has to cut out.", 1, 80, 1,
            new[] { "", "+8% heat capacity" },
            "+8% heat capacity", "+8%"),
        new("m-rerolls", "Rerolls", "Walk into every run holding more second opinions. A reroll deals a fresh three cards and still owes you the pick.", 3, 30, 1,
            new[] { "", "2 rerolls", "4 rerolls", "6 rerolls" },
            "6 rerolls at full", "6"),
        new("m-repair", "Repair Bay", "A small repair clock, running from the first second of the run - a trickle next to Field Repair, and no substitute for finding it, but it never has to be found at all.", 3, 30, 1,
            new[] { "", "1 hp per tick", "2 hp per tick", "3 hp per tick" },
            "3 hp per tick at full", "3"),
    };

    public static WorkshopEntry At(int index) =>
        index >= 0 && index < All.Length
            ? All[index]
            : new WorkshopEntry("", "?", "", 0, 0, 0, System.Array.Empty<string>(), "", "");

    /// <summary>
    /// Throws if this table and the ported catalog have drifted apart.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>THE PAIRING IS POSITIONAL, AND THIS IS WHAT CHECKS IT.</b> Index i here is
    /// <see cref="MetaCatalog"/> index i - that is the format, and <c>Settings.ToMetaTiers</c>
    /// relies on it to turn a saved id into the slot <c>World.Meta.Tiers</c> is keyed by. The two
    /// tables have different authors: this one is GENERATED from <c>META_CATALOG</c>, the ported
    /// catalog is a HAND-MAINTAINED list of named fields. Nothing but this function makes them
    /// agree.
    /// </para>
    /// <para>
    /// IT USED TO COMPARE ONLY THE COUNTS, which catches an upgrade being added and nothing else.
    /// Reordering either table - an ordinary hand edit on the ported side - left the counts equal
    /// and silently repointed every purchase in every save onto a different upgrade: a player who
    /// bought Hull Plating would find they owned Mech Insurance instead, at the same tier, with no
    /// error anywhere.
    /// </para>
    /// </remarks>
    public static void Verify()
    {
        if (All.Length != MetaCatalog.All.Length)
        {
            throw new InvalidOperationException(
                $"WorkshopText holds {All.Length} entries but the catalog has " +
                $"{MetaCatalog.All.Length}. Re-run: npx tsx tools/gen_ui_text.ts");
        }

        for (int i = 0; i < All.Length; i++)
        {
            // THE PORTED CATALOG'S OWN SELF-CONSISTENCY FIRST. Every MetaDef carries the index it
            // is supposed to sit at, so a reordered `MetaCatalog.All` is detectable without
            // reference to anything else - and it has to be, because everything else here is
            // checked against it.
            if (MetaCatalog.All[i].Id != i)
            {
                throw new InvalidOperationException(
                    $"MetaCatalog.All[{i}] carries id {MetaCatalog.All[i].Id}. The array has been " +
                    "reordered away from MetaIds, and World.Meta.Tiers is keyed by position.");
            }

            // THEN ACROSS THE TWO TABLES. Tier counts are independent per upgrade and authored on
            // both sides, which makes them a free checksum on the pairing: almost any slip lands a
            // row beside a catalog entry that can be bought a different number of times.
            if (All[i].Tiers != MetaCatalog.All[i].Tiers)
            {
                throw new InvalidOperationException(
                    $"'{All[i].Id}' sits at index {i} and offers {All[i].Tiers} tiers, but the " +
                    $"catalog entry there offers {MetaCatalog.All[i].Tiers}. The two tables have " +
                    "drifted - a saved purchase would be applied to the wrong upgrade.");
            }
        }
    }
}
