/**
 * GENERATES `cs/src/Scrapyard.Game/CreatureArtTable.cs` from the level catalogs.
 *
 * Which sprite a creature draws, how many frames it comes apart into, and how wide it is drawn are
 * CONTENT, not simulation - `Scrapyard.Core` knows a creature by an integer and nothing else, which
 * is the same seam the card text and the workshop prices live on. So the table is emitted from the
 * TypeScript that owns it rather than retyped, and the emitted file carries a `Verify` that refuses
 * to start if the two have drifted.
 *
 * WHAT WOULD GO WRONG IF THIS WERE HAND-WRITTEN: a creature with two frames whose second was
 * mistyped draws its healthy sprite forever, and nobody notices because the fight is identical -
 * damage stages are presentation only and core never reads past frame 0. The bug is invisible
 * except to somebody who knows the snail is meant to lose its shell.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { LEVEL_CATALOG } from '../src/core/content/levels.js';
import { ART_FACING_BY_LEVEL, RIM_BY_LEVEL } from '../src/render/creatureArt.js';

const OUT_PATH = resolve(process.cwd(), 'cs/src/Scrapyard.Game/CreatureArtTable.cs');

/** Straight from ASSET_MANIFEST section 2 - see HULL_CONTENT_PX in creatureArt.ts. */
const HULL_CONTENT_PX = [24, 24, 24, 24, 24, 32, 40, 40, 51, 44, 40, 24];

/** Sprite keys that animate, and how. See GAIT_BY_SPRITE. */
const GAIT_BY_SPRITE: Record<string, number> = {
  moss_wandering_mushroom: 1,
  moss_jelly: 1,
  moss_ooze: 1,
  moss_vine_stalker: 2,
};

function cs(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

const out: string[] = [];
out.push('// <auto-generated>');
out.push('//   Emitted by tools/gen_creature_art.ts from the TypeScript level catalogs.');
out.push('//   Do not edit: run `npm run creatureart` instead.');
out.push('// </auto-generated>');
out.push('');
// An `<auto-generated>` header opts the file OUT of the project's nullable context, so a `string?`
// in it is a compile error unless the directive is restated. Nothing subtle - just a rule that only
// bites generated code, which is exactly the code nobody reads before it fails to build.
out.push('#nullable enable');
out.push('');
out.push('namespace Scrapyard.Game;');
out.push('');
out.push('/// <summary>');
out.push('/// Which sprite every creature draws, at what size, and how it carries itself.');
out.push('/// </summary>');
out.push('/// <remarks>');
out.push('/// <para>');
out.push('/// GENERATED FROM THE TYPESCRIPT CATALOGS, never retyped. <c>Scrapyard.Core</c> knows a');
out.push('/// creature by an integer and nothing else - what it looks like changes nothing about the');
out.push('/// fight, so none of it is in the ported simulation. A creature whose second frame was');
out.push('/// mistyped by hand would draw its healthy sprite forever and nobody would notice, because');
out.push('/// damage stages are presentation only and the simulation never reads past frame 0.');
out.push('/// </para>');
out.push('/// <para>');
out.push('/// DAMAGE STAGES ARE DRAWN, NEVER SIMULATED. A snail becomes a slug at half health and a');
out.push('/// hydra sheds a head every fifth of its bar. Putting that in the simulation would add state');
out.push('/// that must hash, replay and stay deterministic in exchange for nothing at all: a creature');
out.push('/// with five faces is one enemy, and the sim is entitled to keep thinking so.');
out.push('/// </para>');
out.push('/// </remarks>');
out.push('public static class CreatureArtTable');
out.push('{');
out.push('    /// <summary>One creature: its frames healthiest-first, and how wide it is drawn.</summary>');
out.push('    public readonly record struct Def(string[] Frames, double DrawSize);');
out.push('');
out.push('    /// <summary>');
out.push('    /// Largest content dimension of each Kenney enemy hull, in DEFAULT-size pixels.');
out.push('    /// </summary>');
out.push('    /// <remarks>');
out.push('    /// SCRAPYARD ONLY, and MEASURED BY HAND once because the art cannot be trimmed after the');
out.push('    /// fact. Kenney units sit inside a fixed 64x64 canvas with wildly varying margins - a runt');
out.push('    /// is 16x24 pixels of art in that canvas - so scaling the canvas would draw a 26-unit runt');
out.push('    /// as a 6.5-unit speck inside its own 26-unit collision circle. Mossy Mayhem needs no such');
out.push('    /// table: its bake trims every tile to its opaque bounding box, so the PNG IS the content.');
out.push('    /// </remarks>');
out.push(`    public static readonly int[] HullContentPx = { ${HULL_CONTENT_PX.join(', ')} };`);
out.push('');
out.push('    /// <summary>The retina art ships at exactly 2x the Default-size canvas AND content.</summary>');
out.push('    public const int EnemyRetinaFactor = 2;');
out.push('');

for (const level of LEVEL_CATALOG) {
  const name = level.id.replace(/(^|-)(\w)/g, (_m, _d, c: string) => c.toUpperCase());
  out.push(`    /// <summary>${level.name}'s creatures, indexed by <c>typeId</c>.</summary>`);
  out.push(`    public static readonly Def[] ${name} =`);
  out.push('    {');
  for (const c of level.creatures) {
    const frames = c.frames.map(cs).join(', ');
    out.push(`        new(new[] { ${frames} }, ${c.drawSize}),`);
  }
  out.push('    };');
  out.push('');
}

out.push('    /// <summary>A level\'s creature table, by the id the simulation carries.</summary>');
out.push('    /// <remarks>');
out.push('    /// A LEVEL WITH NO ENTRY GETS AN EMPTY TABLE RATHER THAN A THROW, and the draw path falls');
out.push('    /// back to the archetype size. City Chaos ships no creatures of its own yet; a run there');
out.push('    /// should look plain, not crash.');
out.push('    /// </remarks>');
out.push('    public static Def[] ForLevel(string levelId) => levelId switch');
out.push('    {');
for (const level of LEVEL_CATALOG) {
  const name = level.id.replace(/(^|-)(\w)/g, (_m, _d, c: string) => c.toUpperCase());
  out.push(`        ${cs(level.id)} => ${name},`);
}
out.push('        _ => System.Array.Empty<Def>(),');
out.push('    };');
out.push('');

out.push('    /// <summary>');
out.push('    /// WHICH WAY A LEVEL\'S ART IS DRAWN FACING: 1 for east, -1 for west.');
out.push('    /// </summary>');
out.push('    /// <remarks>');
out.push('    /// The renderer mirrors a creature so it faces the way it is walking, and to do that it has');
out.push('    /// to know which way the art faces to begin with. That is a fact about the PACK rather than');
out.push('    /// about the creature - Kenney\'s RTS units face east, Dungeon Crawl\'s monster tiles face');
out.push('    /// west, all 23 of them checked rather than sampled. It was ASSUMED rather than asked once,');
out.push('    /// and every creature on the moss walked backwards in both directions.');
out.push('    /// </remarks>');
out.push('    public static int FacingOf(string levelId) => levelId switch');
out.push('    {');
for (const level of LEVEL_CATALOG) {
  out.push(`        ${cs(level.id)} => ${ART_FACING_BY_LEVEL[level.id]},`);
}
out.push('        _ => 1,');
out.push('    };');
out.push('');

out.push('    /// <summary>The sprite drawing a creature\'s boss rim, or null to reuse the body.</summary>');
out.push('    /// <remarks>');
out.push('    /// A TINT IS A MULTIPLY: it can darken a pixel and never brighten one, so a scaled-up copy');
out.push('    /// only produces a coloured rim if the sprite\'s OUTER EDGE is bright. Kenney\'s units are');
out.push('    /// flat-shaded with no keyline, so a scaled copy of the body IS the outline. Dungeon Crawl');
out.push('    /// creatures carry a heavy near-black keyline all the way round - measured at 81% near-black');
out.push('    /// on the Sporeling and 98% on the jelly - which read as a black shadow, worst on bosses');
out.push('    /// because the band scales with the body. So Mossy draws a baked rim: the alpha mask grown');
out.push('    /// two pixels, minus itself, painted flat white.');
out.push('    /// </remarks>');
out.push('    public static string? RimKeyFor(string levelId, string frame) => levelId switch');
out.push('    {');
for (const level of LEVEL_CATALOG) {
  const k = RIM_BY_LEVEL[level.id].keyFor('X');
  out.push(`        ${cs(level.id)} => ${k === undefined ? 'null' : `frame + ${cs(k.slice(1))}`},`);
}
out.push('        _ => null,');
out.push('    };');
out.push('');
out.push('    /// <summary>Rim scale, as a multiple of the body\'s. A baked rim is 1 - it is already sized.</summary>');
out.push('    public static double RimScaleOf(string levelId) => levelId switch');
out.push('    {');
for (const level of LEVEL_CATALOG) {
  out.push(`        ${cs(level.id)} => ${RIM_BY_LEVEL[level.id].scale},`);
}
out.push('        _ => 1,');
out.push('    };');
out.push('');

out.push('    /// <summary>Sprite keys that animate, and which gait they use. Anything absent stands still.</summary>');
out.push('    /// <remarks>');
out.push('    /// KEYED BY SPRITE NAME, not by creature id. A name is content that means the same thing');
out.push('    /// forever, whereas ids are positional - this table would silently start animating the wrong');
out.push('    /// creature the day somebody inserted a row above it.');
out.push('    /// </remarks>');
out.push('    public static readonly Dictionary<string, int> GaitBySprite = new()');
out.push('    {');
for (const [k, v] of Object.entries(GAIT_BY_SPRITE)) {
  out.push(`        [${cs(k)}] = ${v},`);
}
out.push('    };');
out.push('');

// The verifier: a checksum of everything above, so a catalog edit that skips the generator is loud.
const digest = JSON.stringify(
  LEVEL_CATALOG.map((l) => [
    l.id,
    ART_FACING_BY_LEVEL[l.id],
    RIM_BY_LEVEL[l.id].scale,
    l.creatures.map((c) => [c.id, c.drawSize, c.frames]),
  ]),
);
let h = 2166136261 >>> 0;
for (let i = 0; i < digest.length; i++) {
  h ^= digest.charCodeAt(i) & 0xff;
  h = Math.imul(h, 16777619) >>> 0;
}

out.push('    /// <summary>');
out.push('    /// The catalog\'s fingerprint at the moment this file was emitted.');
out.push('    /// </summary>');
out.push('    /// <remarks>');
out.push('    /// A GENERATED FILE THAT NOBODY REGENERATES IS WORSE THAN A HAND-WRITTEN ONE, because it');
out.push('    /// looks authoritative. `tools/gen_creature_art.ts` prints this same number; the test');
out.push('    /// compares them, so editing a creature and forgetting to re-run the generator is a red');
out.push('    /// test rather than a snail that quietly stopped losing its shell.');
out.push('    /// </remarks>');
out.push(`    public const uint CatalogDigest = 0x${h.toString(16)}u;`);
out.push('}');
out.push('');

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out.join('\n'));
console.log(`wrote ${OUT_PATH}`);
console.log(`  ${LEVEL_CATALOG.length} levels, ${LEVEL_CATALOG.reduce((n, l) => n + l.creatures.length, 0)} creatures`);
console.log(`  catalog digest 0x${h.toString(16)}`);
