/**
 * Emits the C# front-end's text and shop tables from the catalogs that own them.
 *
 *   npx tsx tools/gen_ui_text.ts
 *
 * Two files, one command:
 *
 *   cs/src/Scrapyard.Game/CardTexts.cs      upgrade card names and descriptions
 *   cs/src/Scrapyard.Meta/WorkshopText.cs   workshop names, blurbs, PRICES and VERSIONS
 *   cs/src/Scrapyard.Meta/UnlockTables.cs   every lock on a chassis, a level and a card
 *   cs/src/Scrapyard.Meta/Achievements.cs   the achievement table, platform keys included
 *
 * WHY GENERATE RATHER THAN PORT. `Scrapyard.Core` knows a card by an integer and a workshop upgrade
 * by its effects: names, blurbs, costs and versions change nothing about what happens, so none of
 * them is in the ported simulation. But the front-end has to draw them and the shop has to charge
 * them, and retyping thirty-seven strings and sixteen prices into another language is how three
 * cards end up wearing each other's names and one upgrade is quietly half price.
 *
 * THE ORDER IS THE FORMAT in both tables: index i is catalog index i. Re-run after adding,
 * renaming or REORDERING anything in either catalog. Both emitted classes carry a `Verify` that
 * refuses to start when the length no longer matches the ported catalog.
 *
 * `version` is load-bearing rather than decorative: it is what a save compares a purchase against,
 * and a mismatch REFUNDS the purchase rather than silently re-pricing it. Bump it in the TypeScript
 * whenever a workshop upgrade's effect changes, and regenerate.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { UPGRADE_CATALOG } from '../src/core/data/upgrades.js';
import { META_CATALOG, metaEffectText } from '../src/core/data/meta.js';
import { HERO_CATALOG } from '../src/core/data/heroes.js';
import { ACHIEVEMENT_CATALOG } from '../src/core/data/achievements.js';
import { LEVEL_CATALOG } from '../src/core/content/levels.js';
import { WEAPON_CATALOG } from '../src/core/data/weapons.js';

function cs(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// ---------------------------------------------------------------------------------------------
// Upgrade card text
// ---------------------------------------------------------------------------------------------

/*
 * THE TIER STRINGS COME TOO, and they are the reason the card in front of a player is worth
 * reading. A card's description says what the weapon IS; `tiers[n]` says what taking it right now
 * would do, and the two are different sentences on every card past the first pick.
 *
 * They live in the TypeScript beside the `perLevel` deltas that implement them, precisely so a
 * balance pass cannot move a number without moving the sentence - which is exactly why they are
 * generated from there rather than retyped here.
 */
const cardRows = UPGRADE_CATALOG.map((u) => {
  const r = u as unknown as Record<string, unknown>;
  const tiers = (r.tiers as readonly string[] | undefined) ?? [];
  const list = tiers.map((t) => `"${cs(t)}"`).join(', ');
  return `        new("${cs(String(r.id))}", "${cs(String(r.name))}", ` +
    `"${cs(String(r.description))}", ${r.kind === 'weapon' ? 'true' : 'false'},\n` +
    `            new[] { ${list} }),`;
}).join('\n');

const cardsSrc = `namespace Scrapyard.Game;

/// <summary>
/// What a card SAYS - its id on disk, its name, and its one line of text.
/// </summary>
/// <remarks>
/// <para>
/// NOT IN <c>Scrapyard.Core</c>, because none of it changes what happens. The simulation knows a
/// card by an integer and by its effects; the words are the player's half of the contract, and they
/// live with the thing that draws them.
/// </para>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c> from <c>src/core/data/upgrades.ts</c> rather than
/// retyped, because retyping 21 descriptions into another language is how three cards end up
/// mislabelled. THE ORDER IS THE FORMAT: index i here is catalog index i there, and
/// <see cref="CardTexts.Verify"/> refuses to start if the two have drifted apart.
/// </para>
/// <para>
/// NO MAGNITUDES, and that rule belongs to the text rather than to this file: a card is read in
/// four seconds with a horde closing in, and "+7% range" invites arithmetic where "every weapon
/// reaches further" invites a decision. Counts of projectiles DO appear, because a third missile is
/// a different thing happening rather than a bigger number.
/// </para>
/// </remarks>
/// <param name="Id">The upgrade's id on disk.</param>
/// <param name="Name">What the card is called.</param>
/// <param name="Description">What the thing IS - shown when a card would unlock it.</param>
/// <param name="Weapon">
/// Ordnance rather than a system. It decides which of two colours the card wears, and a passive
/// announced as a weapon is the kind of small lie that teaches a player the card text cannot be
/// trusted.
/// </param>
/// <param name="Tiers">
/// What each tier DOES, indexed from zero for tier 1. Authored beside the deltas that implement
/// them, so a balance pass cannot move a number without moving the sentence.
/// </param>
public readonly record struct CardText(
    string Id, string Name, string Description, bool Weapon, string[] Tiers)
{
    /// <summary>The upgrade card icons on disk are <c>icon_&lt;id&gt;.png</c>.</summary>
    public string IconKey => "icon_" + Id;

    /// <summary>What tier <paramref name="tier"/> does, or the description if it says nothing.</summary>
    /// <remarks>
    /// FALLS BACK RATHER THAN THROWS. This draws whatever catalog the simulation was built with,
    /// and a card whose tier list is short has to degrade to its description - inside a phase
    /// transition is the worst possible place to discover an off-by-one.
    /// </remarks>
    public string TierAt(int tier) =>
        tier >= 1 && tier <= Tiers.Length ? Tiers[tier - 1] : Description;
}

public static class CardTexts
{
    public static readonly CardText[] All =
    {
${cardRows}
    };

    /// <summary>The text for a catalog index, or a placeholder if the table has gone stale.</summary>
    public static CardText At(int index) =>
        index >= 0 && index < All.Length
            ? All[index]
            : new CardText("", "?", "", false, System.Array.Empty<string>());

    /// <summary>
    /// Throws if this table and the ported catalog have drifted apart.
    /// </summary>
    /// <remarks>
    /// CHECKED AT STARTUP RATHER THAN IN A TEST, because a check that lives where the mistake is
    /// made is worth more than one that lives where it is convenient. A card added to the
    /// TypeScript and not regenerated here would otherwise show up as three cards wearing each
    /// other's names, which is the kind of bug a player reports as "the game lied to me".
    /// </remarks>
    public static void Verify(int catalogCount)
    {
        if (All.Length != catalogCount)
        {
            throw new InvalidOperationException(
                $"CardTexts holds {All.Length} cards but the catalog has {catalogCount}. " +
                "Re-run: npx tsx tools/gen_ui_text.ts");
        }
    }
}
`;

// ---------------------------------------------------------------------------------------------
// Workshop text and prices
// ---------------------------------------------------------------------------------------------

/*
 * THE EFFECT SUMMARIES ARE EMITTED AS STRINGS, one per tier the player could be holding, rather
 * than as the arithmetic that produces them.
 *
 * `metaEffectText` is small, and porting it would mean porting `metaEffectValue`, the per-upgrade
 * `display` metadata, the pluralisation and `oneDecimal` - and then MATCHING JavaScript's number
 * formatting from C#, which is a different rounding rule and a different trailing-zero rule.
 * "+12.9% damage" against "+12.90% damage" is not a bug either language would report; it is a
 * screen quietly disagreeing with the other build about what the player bought.
 *
 * There are 16 upgrades and at most 7 tiers each, so the whole table is under a hundred short
 * strings. Generating them is cheaper than the port and cannot drift.
 */
const shopRows = META_CATALOG.map((m) => {
  const r = m as unknown as Record<string, string | number>;
  const def = m as Parameters<typeof metaEffectText>[0];
  const tiers = Number(r.tiers);

  // Index t is what the row says when t tiers are held. Index 0 is empty by `metaEffectText`'s own
  // contract, and the screen shows `Promise` there instead.
  const summaries: string[] = [];
  for (let t = 0; t <= tiers; t++) summaries.push(metaEffectText(def, t));

  // What the row promises when nothing is owned: the FULL effect, and "at full" after it whenever
  // there is more than one tier to reach.
  const promise = `${metaEffectText(def, tiers)}${tiers > 1 ? ' at full' : ''}`;

  // The tail on a part-bought row drops the noun the head just said - "+12.9% damage : +30% at
  // full" rather than saying "damage" twice in nine words.
  const fullBare = metaEffectText(def, tiers, true);

  const list = summaries.map((t) => `"${cs(t)}"`).join(', ');
  return `        new("${cs(String(r.id))}", "${cs(String(r.name))}", "${cs(String(r.blurb))}", ` +
    `${r.tiers}, ${r.cost}, ${r.version},\n` +
    `            new[] { ${list} },\n` +
    `            "${cs(promise)}", "${cs(fullBare)}"),`;
}).join('\n');

const shopSrc = `using Scrapyard.Core;

namespace Scrapyard.Meta;

/// <summary>
/// What a workshop upgrade SAYS and what it COSTS.
/// </summary>
/// <remarks>
/// <para>
/// NOT IN <c>Scrapyard.Core</c>. The simulation reads a workshop upgrade's EFFECTS and its tier
/// count and nothing else - the name, the blurb, the price and the version are shop economics, and
/// a run that has already started cannot be changed by any of them.
/// </para>
/// <para>
/// <c>Version</c> IS LOAD-BEARING. A save records the version a purchase was made under; when the
/// upgrade's effect later changes, the version bumps and <see cref="Settings"/> REFUNDS the
/// purchase rather than silently handing the player something they did not buy. That is why the
/// number is generated from the catalog rather than assumed to be 1.
/// </para>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c>. THE ORDER IS THE FORMAT: index i here is
/// <c>MetaCatalog.All</c> index i, which is also what <c>World.Meta.Tiers</c> is keyed by.
/// </para>
/// </remarks>
/// <param name="Id">The upgrade's id on disk, which is what a save records.</param>
/// <param name="Name">What the row is called.</param>
/// <param name="Blurb">One or two sentences on what buying it does to a run.</param>
/// <param name="Tiers">How many times it can be bought.</param>
/// <param name="Cost">The price of one tier. Flat: the seventh costs what the first did.</param>
/// <param name="Version">
/// Bumped when the upgrade's effect changes, so a save holding the old one is refunded rather than
/// silently handed something else.
/// </param>
/// <param name="Summary">
/// What the row says the mech HAS, indexed by tiers held. Index 0 is empty - a row with nothing
/// bought has no current effect to state, and shows <paramref name="Promise"/> instead.
/// </param>
/// <param name="Promise">The full effect, worded for a row that owns none of it.</param>
/// <param name="FullBare">
/// The full effect with its noun stripped, for the "+30% at full" tail on a part-bought row.
/// </param>
public readonly record struct WorkshopEntry(
    string Id, string Name, string Blurb, int Tiers, int Cost, int Version,
    string[] Summary, string Promise, string FullBare)
{
    /// <summary>What this row says about a mech holding <paramref name="tiers"/> of it.</summary>
    /// <remarks>
    /// CLAMPED rather than trusted. A save can hold more tiers than the catalog now offers - the
    /// ceiling came down between versions - and the shop still has to draw that row today. The
    /// refund path deals with the overpayment; this only has to say something true.
    /// </remarks>
    public string SummaryAt(int tiers)
    {
        if (Summary.Length == 0) return "";
        int t = tiers < 0 ? 0 : tiers;
        return Summary[t >= Summary.Length ? Summary.Length - 1 : t];
    }
}

public static class WorkshopText
{
    public static readonly WorkshopEntry[] All =
    {
${shopRows}
    };

    public static WorkshopEntry At(int index) =>
        index >= 0 && index < All.Length
            ? All[index]
            : new WorkshopEntry("", "?", "", 0, 0, 0, System.Array.Empty<string>(), "", "");

    /// <summary>
    /// Throws if this table and the ported catalog have drifted apart.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>THE PAIRING IS POSITIONAL, AND THIS IS WHAT CHECKS IT.</b> Index i here is
    /// <see cref="MetaCatalog"/> index i - that is the format, and <c>Settings.ToMetaTiers</c>
    /// relies on it to turn a saved id into the slot <c>World.Meta.Tiers</c> is keyed by. The two
    /// tables have different authors: this one is GENERATED from <c>META_CATALOG</c>, the ported
    /// catalog is a HAND-MAINTAINED list of named fields. Nothing but this function makes them
    /// agree.
    /// </para>
    /// <para>
    /// IT USED TO COMPARE ONLY THE COUNTS, which catches an upgrade being added and nothing else.
    /// Reordering either table - an ordinary hand edit on the ported side - left the counts equal
    /// and silently repointed every purchase in every save onto a different upgrade: a player who
    /// bought Hull Plating would find they owned Mech Insurance instead, at the same tier, with no
    /// error anywhere.
    /// </para>
    /// </remarks>
    public static void Verify()
    {
        if (All.Length != MetaCatalog.All.Length)
        {
            throw new InvalidOperationException(
                $"WorkshopText holds {All.Length} entries but the catalog has " +
                $"{MetaCatalog.All.Length}. Re-run: npx tsx tools/gen_ui_text.ts");
        }

        for (int i = 0; i < All.Length; i++)
        {
            // THE PORTED CATALOG'S OWN SELF-CONSISTENCY FIRST. Every MetaDef carries the index it
            // is supposed to sit at, so a reordered \`MetaCatalog.All\` is detectable without
            // reference to anything else - and it has to be, because everything else here is
            // checked against it.
            if (MetaCatalog.All[i].Id != i)
            {
                throw new InvalidOperationException(
                    $"MetaCatalog.All[{i}] carries id {MetaCatalog.All[i].Id}. The array has been " +
                    "reordered away from MetaIds, and World.Meta.Tiers is keyed by position.");
            }

            // THEN ACROSS THE TWO TABLES. Tier counts are independent per upgrade and authored on
            // both sides, which makes them a free checksum on the pairing: almost any slip lands a
            // row beside a catalog entry that can be bought a different number of times.
            if (All[i].Tiers != MetaCatalog.All[i].Tiers)
            {
                throw new InvalidOperationException(
                    $"'{All[i].Id}' sits at index {i} and offers {All[i].Tiers} tiers, but the " +
                    $"catalog entry there offers {MetaCatalog.All[i].Tiers}. The two tables have " +
                    "drifted - a saved purchase would be applied to the wrong upgrade.");
            }
        }
    }
}
`;

// ---------------------------------------------------------------------------------------------
// Unlock conditions
// ---------------------------------------------------------------------------------------------

/**
 * One condition, as a C# `UnlockCond` factory call.
 *
 * GENERATED RATHER THAN TRANSCRIBED, because a lock retyped wrong is either a chassis nobody can
 * earn or one everybody gets for free, and neither announces itself. The `never` cases are emitted
 * as `never` and NOT quietly given a plausible number: `never` means the criteria have not been
 * written, and inventing one here would be making a design decision by accident.
 */
function condOf(c: unknown): string {
  const u = c as Record<string, unknown> | undefined;
  if (u === undefined) return 'UnlockCond.Never()';
  const w = (id: unknown): string => `WeaponIds.${csEnum(String(id))}`;
  const ws = (ids: unknown): string => (ids as string[]).map(w).join(', ');

  switch (u.kind) {
    case 'always': return 'UnlockCond.Always()';
    case 'never': return 'UnlockCond.Never()';
    case 'wave': return `UnlockCond.Wave(${u.wave})`;
    case 'survive': return `UnlockCond.Survive(${u.sec})`;
    case 'kills': return `UnlockCond.Kills(${u.count})`;
    case 'chassisOwned': return `UnlockCond.ChassisOwned(${u.count})`;
    case 'win': return 'UnlockCond.Win()';
    case 'winLevel': return `UnlockCond.WinLevel("${u.level}")`;
    case 'fullRepair': return 'UnlockCond.FullRepair()';
    case 'lasersOverheated': return 'UnlockCond.LasersOverheated()';
    case 'contactHits': return `UnlockCond.ContactHits(${u.count})`;
    case 'diedTo': return `UnlockCond.DiedTo("${u.rank}")`;
    case 'bossKillHolding': return `UnlockCond.BossKillHolding(${w(u.weapon)})`;
    case 'bossKillBy': return `UnlockCond.BossKillBy(${ws(u.weapons)})`;
    case 'killsWith': return `UnlockCond.KillsWith(${u.count}, ${ws(u.weapons)})`;
    case 'killsWithTotal': return `UnlockCond.KillsWithTotal(${u.count}, ${ws(u.weapons)})`;
    case 'splashKillsTotal': return `UnlockCond.SplashKillsTotal(${u.count})`;
    case 'reloadsTotal': return `UnlockCond.ReloadsTotal(${u.count})`;
    case 'tier': {
      const i = UPGRADE_CATALOG.findIndex((d) => d.id === u.id);
      if (i < 0) throw new Error(`tier condition names an unknown card: ${String(u.id)}`);
      return `UnlockCond.Tier(${i}, ${u.tier})`;
    }
    default: throw new Error(`unhandled unlock kind: ${String(u.kind)}`);
  }
}

/** `missile-short` -> `MissileShort`, matching the C# WeaponIds members. */
function csEnum(id: string): string {
  return id.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
}

/*
 * THE ONE LINE UNDER THE NAME comes along too. A chassis's `identity` and a yard's `blurb` are the
 * only thing either pick screen says about what you are choosing - "Sixteen chassis, eight carry a
 * bonus to one weapon" is the whole difference between them - and a port that drew the name alone
 * would be asking a player to pick blind.
 *
 * `playable` is NOT the same fact as the unlock condition and both are carried. A level can be
 * unfinished (nobody may enter), finished but unearned (locked on this save), or open; the pick
 * screen flags the first "TBD" and the second "LOCKED", and collapsing them would tell a player to
 * go and win something that does not exist yet.
 */
const heroRows = HERO_CATALOG.map((h) => {
  const r = h as unknown as Record<string, unknown>;
  return `        new("${cs(String(r.id))}", "${cs(String(r.name))}", ${condOf(r.unlock)}, ` +
    `"${cs(String(r.identity))}", true, "${cs(String(r.sprite))}"),`;
}).join('\n');

const levelRows = LEVEL_CATALOG.map((l) => {
  const r = l as unknown as Record<string, unknown>;
  return `        new("${cs(String(r.id))}", "${cs(String(r.name))}", ${condOf(r.unlock)}, ` +
    `"${cs(String(r.blurb))}", ${r.playable === true}, "${cs(String(r.art))}"),`;
}).join('\n');

const cardLockRows = UPGRADE_CATALOG
  .map((u, i) => [u, i] as const)
  .filter(([u]) => (u as unknown as Record<string, unknown>).unlock !== undefined)
  .map(([u, i]) => {
    const r = u as unknown as Record<string, unknown>;
    return `        new(${i}, "${cs(String(r.id))}", "${cs(String(r.name))}", ${condOf(r.unlock)}),`;
  })
  .join('\n');

/**
 * EVERY upgrade id, in catalog order, and the ones that carry a tier 8.
 *
 * Emitted into `Scrapyard.Meta` because that is where the SAVE lives, and the save's ids have to be
 * filterable against the catalog without reaching into the drawing layer - which `Scrapyard.Meta`
 * cannot see and must not. `CardTexts` carries the same ids in `Scrapyard.Game` for the screens;
 * both come from this one line, so they cannot disagree.
 *
 * The ascension list names PARENT ids and is emitted as a bare list of strings rather than as
 * anything that says how many there are in total, for the reason the whole ascension apparatus is
 * built the way it is: a count is a leak. It is used to drop a stored id whose tier 8 has been
 * withdrawn, and nothing reads it before then.
 */
const allCardIdRows = UPGRADE_CATALOG
  .map((u) => `        "${cs(String((u as unknown as Record<string, unknown>).id))}",`)
  .join('\n');

const ascendedCardIdRows = UPGRADE_CATALOG
  .filter((u) => (u as unknown as Record<string, unknown>).ascension !== undefined)
  .map((u) => `        "${cs(String((u as unknown as Record<string, unknown>).id))}",`)
  .join('\n');

const unlockSrc = `using Scrapyard.Core;

namespace Scrapyard.Meta;

/// <summary>
/// Every lock in the game, in the one condition language.
/// </summary>
/// <remarks>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c>. A lock retyped wrong is either a chassis nobody can
/// earn or one everybody gets for free, and neither announces itself - so these are emitted from
/// the catalogs that own them rather than copied.
/// </para>
/// <para>
/// <b>THE CRITERIA ARE PUBLISHED NOWHERE.</b> A locked chassis is a silhouette and a question mark.
/// These conditions exist to be EVALUATED, and the only place one is ever stated to a player is the
/// achievement that fires on earning it, in the past tense. There is deliberately no imperative
/// description here and there must not be one.
/// </para>
/// <para>
/// <b><c>Never</c> means the criteria have not been written.</b> Four chassis carry it. It is not a
/// placeholder to be filled in with something plausible: a guessed number is a design decision made
/// by accident, and once shipped it is something players have already played around.
/// </para>
/// </remarks>
/// <param name="Id">What a save records, and what a condition names.</param>
/// <param name="Name">What the pick screen calls it.</param>
/// <param name="Cond">What has to have happened for it to be pickable.</param>
/// <param name="Line">
/// The one line under the name: a chassis's identity, a yard's blurb. It is the only thing either
/// pick screen says about what is being chosen.
/// </param>
/// <param name="Playable">
/// Whether the CONTENT exists, which is a different question from whether this save has earned it.
/// A level can be unfinished, or finished and unearned, or open - and a screen that told a player to
/// go and win something not built yet would be worse than one that said nothing.
/// </param>
/// <param name="Art">
/// The sprite the pick screen shows. NAMED HERE rather than derived from the index, because the
/// index is a fact about a catalog's current order and the art is a fact about the thing.
/// </param>
public readonly record struct LockedThing(
    string Id, string Name, UnlockCond Cond, string Line, bool Playable, string Art);

/// <summary>A card lock, which also carries the catalog index the deck is keyed by.</summary>
public readonly record struct LockedCard(int Index, string Id, string Name, UnlockCond Cond);

/// <summary>
/// Every upgrade id the save may legitimately hold, so a stored one can be resolved.
/// </summary>
/// <remarks>
/// <para>
/// HERE RATHER THAN IN THE DRAWING LAYER, because the save is filtered on load and
/// <see cref="Settings.Reconcile"/> lives in this project. <c>CardTexts</c> in
/// <c>Scrapyard.Game</c> carries the same ids for the screens; both are generated from the same
/// catalog line, so the two cannot drift.
/// </para>
/// <para>
/// <c>Ascended</c> NAMES PARENT IDS AND NOTHING ELSE - not how many there are, not what they
/// become. It exists so a <c>HeldAscensions</c> entry whose tier 8 has since been withdrawn is
/// dropped rather than left claiming a page nothing can draw, which is the same rule every other
/// list follows.
/// </para>
/// </remarks>
public static class CardIds
{
    public static readonly string[] All =
    {
${allCardIdRows}
    };

    /// <summary>The cards that HAVE a tier 8, by their own id.</summary>
    public static readonly string[] Ascended =
    {
${ascendedCardIdRows}
    };
}

public sealed class HeroUnlocks
{
    public static readonly LockedThing[] Heroes =
    {
${heroRows}
    };

    public static readonly LockedThing[] Levels =
    {
${levelRows}
    };

    /// <summary>The cards that must be EARNED. Everything not listed is offerable from the start.</summary>
    public static readonly LockedCard[] Cards =
    {
${cardLockRows}
    };

    /// <summary>
    /// Which chassis this run has just earned, by catalog index.
    /// </summary>
    /// <remarks>
    /// A SET UNION: anything the save already owns is skipped, so this reports each unlock exactly
    /// once however often it is called. That is what makes banking once a second free.
    /// </remarks>
    public IEnumerable<int> NewlyUnlocked(Settings save, RunRecord run, CareerRecord career)
    {
        for (int i = 0; i < Heroes.Length; i++)
        {
            var h = Heroes[i];
            if (save.UnlockedHeroes.Contains(h.Id)) continue;
            if (!Unlocks.Meets(h.Cond, run, career)) continue;
            yield return i;
        }
    }

    public IEnumerable<string> NewlyUnlockedLevels(Settings save, RunRecord run, CareerRecord career)
    {
        foreach (var l in Levels)
        {
            if (save.UnlockedLevels.Contains(l.Id)) continue;
            if (!Unlocks.Meets(l.Cond, run, career)) continue;
            yield return l.Id;
        }
    }

    public IEnumerable<LockedCard> NewlyEarnedCards(Settings save, RunRecord run, CareerRecord career)
    {
        foreach (var c in Cards)
        {
            if (save.EarnedCards.Contains(c.Id)) continue;
            if (!Unlocks.Meets(c.Cond, run, career)) continue;
            yield return c;
        }
    }

    public static void Verify(int heroCount)
    {
        if (Heroes.Length != heroCount)
        {
            throw new InvalidOperationException(
                $"HeroUnlocks holds {Heroes.Length} chassis but the catalog has {heroCount}. " +
                "Re-run: npx tsx tools/gen_ui_text.ts");
        }
    }
}
`;

const unlockOut = resolve(process.cwd(), 'cs/src/Scrapyard.Meta/UnlockTables.cs');
writeFileSync(unlockOut, unlockSrc);
console.log(`wrote ${unlockOut}  (${HERO_CATALOG.length} chassis, ${LEVEL_CATALOG.length} levels)`);
void WEAPON_CATALOG;

// ---------------------------------------------------------------------------------------------
// Achievements
// ---------------------------------------------------------------------------------------------

/**
 * The achievement table, with the DERIVED entries already derived.
 *
 * `MECH_ACHIEVEMENTS` and the level entries are generated in the TypeScript from the chassis and
 * level unlocks, and their descriptions come from `describeUnlockDone`. Emitting the RESOLVED table
 * keeps that derivation in one place: the C# side gets the same condition object the roster got,
 * from the same run of the same generator, so the two cannot disagree about what a condition means.
 * `AchievementTests` then pins the invariant on the C# side as well, so a hand-edit to either table
 * fails rather than quietly parting them.
 *
 * `platformKey` IS PERMANENT. Game Center and Steam both treat their identifier as un-renameable -
 * you cannot change one after a player has earned it without orphaning their copy. It is
 * transcribed here exactly, never derived from the C# side, and retiring an achievement means
 * removing the entry rather than reusing its key.
 */
const achRows = ACHIEVEMENT_CATALOG.map((a) => {
  const r = a as unknown as Record<string, unknown>;
  return `        new("${cs(String(r.id))}", "${cs(String(r.platformKey))}", "${cs(String(r.name))}", ` +
    `"${cs(String(r.description))}", "${cs(String(r.icon))}", ${r.secret === true}, ${condOf(r.cond)}),`;
}).join('\n');

const achSrc = `using Scrapyard.Core;

namespace Scrapyard.Meta;

/// <summary>
/// One achievement: what it is called, what it says once earned, and the condition behind it.
/// </summary>
/// <remarks>
/// <para>
/// <b><c>PlatformKey</c> IS PERMANENT ONCE SHIPPED.</b> Game Center and Steam each want their own
/// identifier, minted in their own console, and both treat it as un-renameable: you cannot change
/// one after a player has earned it without orphaning their copy. <see cref="Id"/> is ours and may
/// be renamed whenever it reads better - the two must never be the same string, and retiring an
/// achievement means removing the entry rather than reusing its key.
/// </para>
/// <para>
/// <b><see cref="Description"/> IS IN THE PAST TENSE, and it is the only place a condition is ever
/// stated to a player.</b> "Reached wave 3", never "Reach wave 3". The criteria are published
/// nowhere else: a locked chassis is a silhouette and a question mark, and the achievement that
/// fires on earning it is the whole of the explanation.
/// </para>
/// <para>
/// <b>SECRET MEANS THE NAME IS HIDDEN UNTIL EARNED.</b> "Unlock the Chain Laser" is a sentence that
/// tells you a Chain Laser exists, that a Medium Laser becomes one, and that there is something to
/// go looking for - which was taken out of the manual on purpose. An achievement list is exactly
/// the back door that would come in through.
/// </para>
/// </remarks>
public readonly record struct AchievementDef(
    string Id, string PlatformKey, string Name, string Description, string Icon, bool Secret,
    UnlockCond Cond);

public static class Achievements
{
    /// <summary>
    /// ORDER IS PRESENTATION ORDER and nothing else. Nothing indexes into this - the save stores
    /// earned achievements by <c>Id</c> - so it can be reordered freely.
    /// </summary>
    public static readonly AchievementDef[] All =
    {
${achRows}
    };

    /// <summary>
    /// Which achievements this run has just earned.
    /// </summary>
    /// <remarks>
    /// A SET UNION against the save, like every other recorder, so calling it once a second reports
    /// each one exactly once.
    /// </remarks>
    public static IEnumerable<AchievementDef> NewlyEarned(Settings save, RunRecord run,
                                                          CareerRecord career)
    {
        foreach (var a in All)
        {
            if (save.UnlockedAchievements.Contains(a.Id)) continue;
            if (!Unlocks.Meets(a.Cond, run, career)) continue;
            yield return a;
        }
    }

    /// <summary>How many are earned, and out of how many.</summary>
    public static (int Earned, int Total) Tally(Settings save)
    {
        int n = 0;
        foreach (var a in All)
        {
            if (save.UnlockedAchievements.Contains(a.Id)) n++;
        }
        return (n, All.Length);
    }

    /// <summary>
    /// What to show in a list: a secret nobody has earned shows nothing but its shape.
    /// </summary>
    public static (string Name, string Description) Display(AchievementDef a, bool earned)
    {
        if (a.Secret && !earned) return ("? ? ?", "");
        return (a.Name, a.Description);
    }
}
`;

const achOut = resolve(process.cwd(), 'cs/src/Scrapyard.Meta/Achievements.cs');
writeFileSync(achOut, achSrc);
console.log(`wrote ${achOut}  (${ACHIEVEMENT_CATALOG.length} achievements)`);

const cardsOut = resolve(process.cwd(), 'cs/src/Scrapyard.Game/CardTexts.cs');
const shopOut = resolve(process.cwd(), 'cs/src/Scrapyard.Meta/WorkshopText.cs');
writeFileSync(cardsOut, cardsSrc);
writeFileSync(shopOut, shopSrc);
console.log(`wrote ${cardsOut}  (${UPGRADE_CATALOG.length} cards)`);
console.log(`wrote ${shopOut}  (${META_CATALOG.length} workshop upgrades)`);
