/**
 * GENERATES `cs/src/Scrapyard.Game/SfxTable.cs` from the render layer's own sound tables.
 *
 * ---------------------------------------------------------------------------------------------
 * WHY THIS IS GENERATED WHEN THE REST OF THE PORT IS HAND-MIRRORED
 * ---------------------------------------------------------------------------------------------
 * Almost everything in `cs/` is a hand transcription of its TypeScript counterpart, kept honest by
 * the golden corpus: if a number is wrong the fixtures disagree and a test goes red. The sound
 * tables have no such backstop. NOTHING ABOUT SOUND IS IN THE WORLD HASH - a muted run and a loud
 * one are the same run, by design - so a gain typed as 0.28 here and 0.82 there produces two games
 * that sound different and zero failing tests. The only way that stays correct is if there is one
 * authored copy, which is the TypeScript one.
 *
 * The MIX is what travels: which clips exist, how loud each is, how often it may repeat, which gun
 * plays which, and which event kinds are silent. Those are numbers, and numbers drift.
 *
 * The ROUTERS do not travel. `blastSfxFor`, `hitSfxFor` and friends are four lines of branching
 * each and are hand-mirrored in `Sfx.cs`, the same way `Damage.cs` mirrors `damage.ts`. Emitting
 * control flow into another language buys nothing and reads far worse than the ten lines it saves.
 *
 * ---------------------------------------------------------------------------------------------
 * TWO ASSUMPTIONS IT CHECKS RATHER THAN TRUSTS
 * ---------------------------------------------------------------------------------------------
 * The event table is emitted as an array INDEXED BY EVENT KIND, and the firing table as one
 * indexed by WEAPON DEF ID, because both are dense small integers that already mean the same thing
 * in both languages. Both of those are load-bearing, so both are verified against the C# source
 * rather than assumed: a weapon inserted into the middle of one catalog and appended to the other
 * would otherwise silently give the Mortar the Cannon's voice, with nothing to catch it.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { WEAPON_CATALOG } from '../src/core/content/weaponCatalog.js';
import { EVENT_NAMES } from '../src/core/events/ring.js';
import { SFX_CATALOG, type SfxId } from '../src/render/audio/sfxCatalog.js';
import {
  BLAST_MEDIUM_MAX,
  BLAST_SMALL_MAX,
  EVENT_SFX,
  FIRE_SFX,
} from '../src/render/audio/sfxTriggers.js';

const OUT_PATH = resolve(process.cwd(), 'cs/src/Scrapyard.Game/SfxTable.cs');
const CS_WEAPONS = resolve(process.cwd(), 'cs/src/Scrapyard.Core/WeaponCatalog.cs');
const CS_RING = resolve(process.cwd(), 'cs/src/Scrapyard.Core/EventRing.cs');

/** `fire_cannon` -> `FireCannon`. The enum member; the CLIP keeps the snake_case filename. */
const pascalSnake = (s: string): string =>
  s.split('_').map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');

/** `machine-gun` -> `MachineGun`, matching how the C# constant spells it. */
const pascalKebab = (s: string): string =>
  s.split('-').map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');

// ---------------------------------------------------------------------------------------------
// CHECK THE TWO INDEXINGS BEFORE EMITTING ANYTHING
// ---------------------------------------------------------------------------------------------
const problems: string[] = [];

const csWeaponSrc = readFileSync(CS_WEAPONS, 'utf8');
const idsStart = csWeaponSrc.indexOf('class WeaponIds');
const idsBlock = csWeaponSrc.slice(idsStart, csWeaponSrc.indexOf('}', idsStart));
const csWeapons = new Map<string, number>();
for (const m of idsBlock.matchAll(/(\w+)\s*=\s*(\d+);/g)) csWeapons.set(m[1], Number(m[2]));

WEAPON_CATALOG.forEach((wp, i) => {
  const want = pascalKebab(wp.id);
  const got = csWeapons.get(want);
  if (got === undefined) problems.push(`WeaponIds has no ${want} (for '${wp.id}')`);
  else if (got !== i) problems.push(`'${wp.id}' is ${i} here but WeaponIds.${want} = ${got}`);
});

const csKinds = new Map<number, string>();
for (const m of readFileSync(CS_RING, 'utf8').matchAll(/public const int (\w+) = (\d+);/g)) {
  csKinds.set(Number(m[2]), m[1]);
}
if (csKinds.size !== EVENT_NAMES.length) {
  problems.push(`EventKind has ${csKinds.size} members, the ring declares ${EVENT_NAMES.length}`);
}

if (problems.length > 0) {
  console.error('  THE TWO CATALOGS HAVE DRIFTED - the emitted tables would be wrong:');
  for (const p of problems) console.error(`    !! ${p}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------------------------
const out: string[] = [];
const w = (s = ''): void => void out.push(s);
const events = EVENT_SFX as Readonly<Record<number, SfxId | null>>;

w('// <auto-generated />');
w('// Generated by tools/gen_sfx_table.ts - `npm run sfxtable`. DO NOT EDIT BY HAND.');
w('//');
w('// The mix lives in src/render/audio/sfxCatalog.ts and sfxTriggers.ts, which are the one');
w('// authored copy for both front-ends. Nothing about sound is in the world hash, so a value');
w('// mistyped here would change how the desktop build sounds and fail no test anywhere - which');
w("// is exactly why this file is emitted rather than transcribed. See the generator's header.");
w();
w('namespace Scrapyard.Game;');
w();
w('/// <summary>Which mixer group a sound belongs to. One volume per bus, never one per clip.</summary>');
w('public enum SfxBus');
w('{');
for (const bus of [...new Set(SFX_CATALOG.map((d) => d.bus))]) w(`    ${pascalSnake(bus)},`);
w('}');
w();
w(`/// <summary>Every sound the game is allowed to make. ${SFX_CATALOG.length} of them.</summary>`);
w('public enum SfxId');
w('{');
for (const d of SFX_CATALOG) w(`    ${pascalSnake(d.id)},`);
w('}');
w();
w('/// <summary>One row of the library. See <c>sfxCatalog.ts</c> for what each column means.</summary>');
w('/// <param name="Clip">Resolves to <c>cs/assets/sfx/&lt;clip&gt;.wav</c>.</param>');
w('/// <param name="ThrottleMs">The floor between two plays. 0 means "cannot double up".</param>');
w('/// <param name="Gain">Baseline gain before the bus fader. A gem is never as loud as a boss.</param>');
w('/// <param name="Loop">True for the beams, which run until told to stop rather than firing once.</param>');
w('public readonly record struct SfxDef(');
w('    SfxId Id, string Clip, SfxBus Bus, int ThrottleMs, float Gain, bool Loop, string Brief);');
w();
w('public static class SfxTable');
w('{');
w('    /// <summary>The library, in the order the brief lays it out.</summary>');
w('    public static readonly SfxDef[] All =');
w('    [');
for (const d of SFX_CATALOG) {
  const brief = d.brief.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  w(
    `        new(SfxId.${pascalSnake(d.id)}, "${d.clip}", SfxBus.${pascalSnake(d.bus)}, ` +
      `${d.throttleMs}, ${d.gain}f, ${d.loop === true ? 'true' : 'false'}, "${brief}"),`,
  );
}
w('    ];');
w();
w('    /// <summary>');
w('    /// ONE SOUND PER EVENT KIND, indexed by the kind itself, or null for the majority that are');
w('    /// a visual fact only. Routed kinds carry a FALLBACK rather than null, so a router that is');
w('    /// ever missed still makes the right KIND of noise - see <c>Sfx.PlayFor</c>.');
w('    /// </summary>');
w('    public static readonly SfxId?[] ByEvent =');
w('    [');
for (let k = 0; k < EVENT_NAMES.length; k++) {
  const id = events[k] ?? null;
  const cell = `        ${id === null ? 'null' : `SfxId.${pascalSnake(id)}`},`;
  w(`${cell.padEnd(38)}// ${k} ${csKinds.get(k) ?? EVENT_NAMES[k]}`);
}
w('    ];');
w();
w('    /// <summary>');
w('    /// WHAT EACH GUN SOUNDS LIKE, indexed by weapon def id. Fourteen weapons, fourteen clips,');
w('    /// and no sharing. The three beams name their LOOP, which is what <c>Sfx.FireSfxFor</c>');
w('    /// turns into silence when a one-shot would otherwise be fired.');
w('    /// </summary>');
w('    public static readonly SfxId[] FireByWeapon =');
w('    [');
WEAPON_CATALOG.forEach((wp, i) => {
  w(`        SfxId.${pascalSnake(FIRE_SFX[wp.id])},`.padEnd(38) + `// ${i} ${wp.id}`);
});
w('    ];');
w();
w('    /// <summary>Blast grades, by radius. See <c>sfxTriggers.ts</c> for why these boundaries.</summary>');
w(`    public const double BlastSmallMax = ${BLAST_SMALL_MAX};`);
w(`    public const double BlastMediumMax = ${BLAST_MEDIUM_MAX};`);
w('}');
w();

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out.join('\n'));

const voiced = EVENT_NAMES.filter((_, k) => (events[k] ?? null) !== null).length;
console.log(`wrote ${OUT_PATH}`);
console.log(`  ${SFX_CATALOG.length} clips, ${WEAPON_CATALOG.length} guns, ${EVENT_NAMES.length} event kinds`);
console.log(`  ${voiced} event kinds voiced, ${EVENT_NAMES.length - voiced} deliberately silent`);
