/**
 * Emits the C# front-end's text and shop tables from the catalogs that own them.
 *
 *   npx tsx tools/gen_ui_text.ts
 *
 * Two files, one command:
 *
 *   cs/src/Scrapyard.Game/CardTexts.cs      upgrade card names and descriptions
 *   cs/src/Scrapyard.Meta/WorkshopText.cs   workshop names, blurbs, PRICES and VERSIONS
 *   cs/src/Scrapyard.Meta/UnlockTables.cs   every lock on a chassis, a level and a card
 *
 * WHY GENERATE RATHER THAN PORT. `Scrapyard.Core` knows a card by an integer and a workshop upgrade
 * by its effects: names, blurbs, costs and versions change nothing about what happens, so none of
 * them is in the ported simulation. But the front-end has to draw them and the shop has to charge
 * them, and retyping thirty-seven strings and sixteen prices into another language is how three
 * cards end up wearing each other's names and one upgrade is quietly half price.
 *
 * THE ORDER IS THE FORMAT in both tables: index i is catalog index i. Re-run after adding,
 * renaming or REORDERING anything in either catalog. Both emitted classes carry a `Verify` that
 * refuses to start when the length no longer matches the ported catalog.
 *
 * `version` is load-bearing rather than decorative: it is what a save compares a purchase against,
 * and a mismatch REFUNDS the purchase rather than silently re-pricing it. Bump it in the TypeScript
 * whenever a workshop upgrade's effect changes, and regenerate.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { UPGRADE_CATALOG } from '../src/core/data/upgrades.js';
import { META_CATALOG } from '../src/core/data/meta.js';
import { HERO_CATALOG } from '../src/core/data/heroes.js';
import { LEVEL_CATALOG } from '../src/core/content/levels.js';
import { WEAPON_CATALOG } from '../src/core/data/weapons.js';

function cs(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// ---------------------------------------------------------------------------------------------
// Upgrade card text
// ---------------------------------------------------------------------------------------------

const cardRows = UPGRADE_CATALOG.map((u) => {
  const r = u as unknown as Record<string, string>;
  return `        new("${cs(r.id)}", "${cs(r.name)}", "${cs(r.description)}"),`;
}).join('\n');

const cardsSrc = `namespace Scrapyard.Game;

/// <summary>
/// What a card SAYS - its id on disk, its name, and its one line of text.
/// </summary>
/// <remarks>
/// <para>
/// NOT IN <c>Scrapyard.Core</c>, because none of it changes what happens. The simulation knows a
/// card by an integer and by its effects; the words are the player's half of the contract, and they
/// live with the thing that draws them.
/// </para>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c> from <c>src/core/data/upgrades.ts</c> rather than
/// retyped, because retyping 21 descriptions into another language is how three cards end up
/// mislabelled. THE ORDER IS THE FORMAT: index i here is catalog index i there, and
/// <see cref="CardTexts.Verify"/> refuses to start if the two have drifted apart.
/// </para>
/// <para>
/// NO MAGNITUDES, and that rule belongs to the text rather than to this file: a card is read in
/// four seconds with a horde closing in, and "+7% range" invites arithmetic where "every weapon
/// reaches further" invites a decision. Counts of projectiles DO appear, because a third missile is
/// a different thing happening rather than a bigger number.
/// </para>
/// </remarks>
public readonly record struct CardText(string Id, string Name, string Description)
{
    /// <summary>The upgrade card icons on disk are <c>icon_&lt;id&gt;.png</c>.</summary>
    public string IconKey => "icon_" + Id;
}

public static class CardTexts
{
    public static readonly CardText[] All =
    {
${cardRows}
    };

    /// <summary>The text for a catalog index, or a placeholder if the table has gone stale.</summary>
    public static CardText At(int index) =>
        index >= 0 && index < All.Length ? All[index] : new CardText("", "?", "");

    /// <summary>
    /// Throws if this table and the ported catalog have drifted apart.
    /// </summary>
    /// <remarks>
    /// CHECKED AT STARTUP RATHER THAN IN A TEST, because a check that lives where the mistake is
    /// made is worth more than one that lives where it is convenient. A card added to the
    /// TypeScript and not regenerated here would otherwise show up as three cards wearing each
    /// other's names, which is the kind of bug a player reports as "the game lied to me".
    /// </remarks>
    public static void Verify(int catalogCount)
    {
        if (All.Length != catalogCount)
        {
            throw new InvalidOperationException(
                $"CardTexts holds {All.Length} cards but the catalog has {catalogCount}. " +
                "Re-run: npx tsx tools/gen_ui_text.ts");
        }
    }
}
`;

// ---------------------------------------------------------------------------------------------
// Workshop text and prices
// ---------------------------------------------------------------------------------------------

const shopRows = META_CATALOG.map((m) => {
  const r = m as unknown as Record<string, string | number>;
  return `        new("${cs(String(r.id))}", "${cs(String(r.name))}", "${cs(String(r.blurb))}", ` +
    `${r.tiers}, ${r.cost}, ${r.version}),`;
}).join('\n');

const shopSrc = `namespace Scrapyard.Meta;

/// <summary>
/// What a workshop upgrade SAYS and what it COSTS.
/// </summary>
/// <remarks>
/// <para>
/// NOT IN <c>Scrapyard.Core</c>. The simulation reads a workshop upgrade's EFFECTS and its tier
/// count and nothing else - the name, the blurb, the price and the version are shop economics, and
/// a run that has already started cannot be changed by any of them.
/// </para>
/// <para>
/// <c>Version</c> IS LOAD-BEARING. A save records the version a purchase was made under; when the
/// upgrade's effect later changes, the version bumps and <see cref="Settings"/> REFUNDS the
/// purchase rather than silently handing the player something they did not buy. That is why the
/// number is generated from the catalog rather than assumed to be 1.
/// </para>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c>. THE ORDER IS THE FORMAT: index i here is
/// <c>MetaCatalog.All</c> index i, which is also what <c>World.Meta.Tiers</c> is keyed by.
/// </para>
/// </remarks>
public readonly record struct WorkshopEntry(
    string Id, string Name, string Blurb, int Tiers, int Cost, int Version);

public static class WorkshopText
{
    public static readonly WorkshopEntry[] All =
    {
${shopRows}
    };

    public static WorkshopEntry At(int index) =>
        index >= 0 && index < All.Length ? All[index] : new WorkshopEntry("", "?", "", 0, 0, 0);

    /// <summary>Throws if this table and the ported catalog have drifted apart.</summary>
    public static void Verify(int catalogCount)
    {
        if (All.Length != catalogCount)
        {
            throw new InvalidOperationException(
                $"WorkshopText holds {All.Length} entries but the catalog has {catalogCount}. " +
                "Re-run: npx tsx tools/gen_ui_text.ts");
        }
    }
}
`;

// ---------------------------------------------------------------------------------------------
// Unlock conditions
// ---------------------------------------------------------------------------------------------

/**
 * One condition, as a C# `UnlockCond` factory call.
 *
 * GENERATED RATHER THAN TRANSCRIBED, because a lock retyped wrong is either a chassis nobody can
 * earn or one everybody gets for free, and neither announces itself. The `never` cases are emitted
 * as `never` and NOT quietly given a plausible number: `never` means the criteria have not been
 * written, and inventing one here would be making a design decision by accident.
 */
function condOf(c: unknown): string {
  const u = c as Record<string, unknown> | undefined;
  if (u === undefined) return 'UnlockCond.Never()';
  const w = (id: unknown): string => `WeaponIds.${csEnum(String(id))}`;
  const ws = (ids: unknown): string => (ids as string[]).map(w).join(', ');

  switch (u.kind) {
    case 'always': return 'UnlockCond.Always()';
    case 'never': return 'UnlockCond.Never()';
    case 'wave': return `UnlockCond.Wave(${u.wave})`;
    case 'survive': return `UnlockCond.Survive(${u.sec})`;
    case 'kills': return `UnlockCond.Kills(${u.count})`;
    case 'chassisOwned': return `UnlockCond.ChassisOwned(${u.count})`;
    case 'win': return 'UnlockCond.Win()';
    case 'winLevel': return `UnlockCond.WinLevel("${u.level}")`;
    case 'fullRepair': return 'UnlockCond.FullRepair()';
    case 'lasersOverheated': return 'UnlockCond.LasersOverheated()';
    case 'contactHits': return `UnlockCond.ContactHits(${u.count})`;
    case 'diedTo': return `UnlockCond.DiedTo("${u.rank}")`;
    case 'bossKillHolding': return `UnlockCond.BossKillHolding(${w(u.weapon)})`;
    case 'bossKillBy': return `UnlockCond.BossKillBy(${ws(u.weapons)})`;
    case 'killsWith': return `UnlockCond.KillsWith(${u.count}, ${ws(u.weapons)})`;
    case 'killsWithTotal': return `UnlockCond.KillsWithTotal(${u.count}, ${ws(u.weapons)})`;
    case 'splashKillsTotal': return `UnlockCond.SplashKillsTotal(${u.count})`;
    case 'reloadsTotal': return `UnlockCond.ReloadsTotal(${u.count})`;
    case 'tier': {
      const i = UPGRADE_CATALOG.findIndex((d) => d.id === u.id);
      if (i < 0) throw new Error(`tier condition names an unknown card: ${String(u.id)}`);
      return `UnlockCond.Tier(${i}, ${u.tier})`;
    }
    default: throw new Error(`unhandled unlock kind: ${String(u.kind)}`);
  }
}

/** `missile-short` -> `MissileShort`, matching the C# WeaponIds members. */
function csEnum(id: string): string {
  return id.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
}

const heroRows = HERO_CATALOG.map((h) => {
  const r = h as unknown as Record<string, unknown>;
  return `        new("${cs(String(r.id))}", "${cs(String(r.name))}", ${condOf(r.unlock)}),`;
}).join('\n');

const levelRows = LEVEL_CATALOG.map((l) => {
  const r = l as unknown as Record<string, unknown>;
  return `        new("${cs(String(r.id))}", "${cs(String(r.name))}", ${condOf(r.unlock)}),`;
}).join('\n');

const cardLockRows = UPGRADE_CATALOG
  .map((u, i) => [u, i] as const)
  .filter(([u]) => (u as unknown as Record<string, unknown>).unlock !== undefined)
  .map(([u, i]) => {
    const r = u as unknown as Record<string, unknown>;
    return `        new(${i}, "${cs(String(r.id))}", "${cs(String(r.name))}", ${condOf(r.unlock)}),`;
  })
  .join('\n');

const unlockSrc = `using Scrapyard.Core;

namespace Scrapyard.Meta;

/// <summary>
/// Every lock in the game, in the one condition language.
/// </summary>
/// <remarks>
/// <para>
/// GENERATED by <c>tools/gen_ui_text.ts</c>. A lock retyped wrong is either a chassis nobody can
/// earn or one everybody gets for free, and neither announces itself - so these are emitted from
/// the catalogs that own them rather than copied.
/// </para>
/// <para>
/// <b>THE CRITERIA ARE PUBLISHED NOWHERE.</b> A locked chassis is a silhouette and a question mark.
/// These conditions exist to be EVALUATED, and the only place one is ever stated to a player is the
/// achievement that fires on earning it, in the past tense. There is deliberately no imperative
/// description here and there must not be one.
/// </para>
/// <para>
/// <b><c>Never</c> means the criteria have not been written.</b> Four chassis carry it. It is not a
/// placeholder to be filled in with something plausible: a guessed number is a design decision made
/// by accident, and once shipped it is something players have already played around.
/// </para>
/// </remarks>
public readonly record struct LockedThing(string Id, string Name, UnlockCond Cond);

/// <summary>A card lock, which also carries the catalog index the deck is keyed by.</summary>
public readonly record struct LockedCard(int Index, string Id, string Name, UnlockCond Cond);

public sealed class HeroUnlocks
{
    public static readonly LockedThing[] Heroes =
    {
${heroRows}
    };

    public static readonly LockedThing[] Levels =
    {
${levelRows}
    };

    /// <summary>The cards that must be EARNED. Everything not listed is offerable from the start.</summary>
    public static readonly LockedCard[] Cards =
    {
${cardLockRows}
    };

    /// <summary>
    /// Which chassis this run has just earned, by catalog index.
    /// </summary>
    /// <remarks>
    /// A SET UNION: anything the save already owns is skipped, so this reports each unlock exactly
    /// once however often it is called. That is what makes banking once a second free.
    /// </remarks>
    public IEnumerable<int> NewlyUnlocked(Settings save, RunRecord run, CareerRecord career)
    {
        for (int i = 0; i < Heroes.Length; i++)
        {
            var h = Heroes[i];
            if (save.UnlockedHeroes.Contains(h.Id)) continue;
            if (!Unlocks.Meets(h.Cond, run, career)) continue;
            yield return i;
        }
    }

    public IEnumerable<string> NewlyUnlockedLevels(Settings save, RunRecord run, CareerRecord career)
    {
        foreach (var l in Levels)
        {
            if (save.UnlockedLevels.Contains(l.Id)) continue;
            if (!Unlocks.Meets(l.Cond, run, career)) continue;
            yield return l.Id;
        }
    }

    public IEnumerable<LockedCard> NewlyEarnedCards(Settings save, RunRecord run, CareerRecord career)
    {
        foreach (var c in Cards)
        {
            if (save.EarnedCards.Contains(c.Id)) continue;
            if (!Unlocks.Meets(c.Cond, run, career)) continue;
            yield return c;
        }
    }

    public static void Verify(int heroCount)
    {
        if (Heroes.Length != heroCount)
        {
            throw new InvalidOperationException(
                $"HeroUnlocks holds {Heroes.Length} chassis but the catalog has {heroCount}. " +
                "Re-run: npx tsx tools/gen_ui_text.ts");
        }
    }
}
`;

const unlockOut = resolve(process.cwd(), 'cs/src/Scrapyard.Meta/UnlockTables.cs');
writeFileSync(unlockOut, unlockSrc);
console.log(`wrote ${unlockOut}  (${HERO_CATALOG.length} chassis, ${LEVEL_CATALOG.length} levels)`);
void WEAPON_CATALOG;

const cardsOut = resolve(process.cwd(), 'cs/src/Scrapyard.Game/CardTexts.cs');
const shopOut = resolve(process.cwd(), 'cs/src/Scrapyard.Meta/WorkshopText.cs');
writeFileSync(cardsOut, cardsSrc);
writeFileSync(shopOut, shopSrc);
console.log(`wrote ${cardsOut}  (${UPGRADE_CATALOG.length} cards)`);
console.log(`wrote ${shopOut}  (${META_CATALOG.length} workshop upgrades)`);
