/**
 * Emits `cs/src/Scrapyard.Game/CardTexts.cs` from the upgrade catalog.
 *
 * The C# core knows a card by an integer: names and descriptions change nothing about what happens,
 * so they are not in the ported simulation. But the front-end has to draw them, and retyping 21
 * descriptions into another language is how three cards end up mislabelled. So they are generated
 * from the one source that owns them.
 *
 *   npx tsx tools/gen_card_text.ts
 *
 * Run it after adding, renaming or REORDERING a card. The order is the format - index i in the
 * emitted table is catalog index i here - and `CardTexts.Verify` on the C# side checks the length
 * against the ported catalog at startup, so a table left stale after a card is added fails loudly
 * instead of mislabelling three cards.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { UPGRADE_CATALOG } from '../src/core/data/upgrades.js';

function csharpString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

const rows = UPGRADE_CATALOG.map((u) => {
  const r = u as unknown as Record<string, string>;
  return `        new("${csharpString(r.id)}", "${csharpString(r.name)}", "${csharpString(r.description)}"),`;
}).join('\n');

const src = `namespace Scrapyard.Game;

/// <summary>
/// What a card SAYS - its id on disk, its name, and its one line of text.
/// </summary>
/// <remarks>
/// <para>
/// NOT IN <c>Scrapyard.Core</c>, because none of it changes what happens. The simulation knows a
/// card by an integer and by its effects; the words are the player's half of the contract, and they
/// live with the thing that draws them.
/// </para>
/// <para>
/// GENERATED by <c>tools/gen_card_text.ts</c> from <c>src/core/data/upgrades.ts</c> rather than
/// retyped, because retyping 21 descriptions into another language is how three cards end up
/// mislabelled. THE ORDER IS THE FORMAT: index i here is catalog index i there, and
/// <see cref="CardTexts.Verify"/> refuses to start if the two have drifted apart.
/// </para>
/// <para>
/// NO MAGNITUDES, and that rule belongs to the text rather than to this file: a card is read in
/// four seconds with a horde closing in, and "+7% range" invites arithmetic where "every weapon
/// reaches further" invites a decision. Counts of projectiles DO appear, because a third missile is
/// a different thing happening rather than a bigger number.
/// </para>
/// </remarks>
public readonly record struct CardText(string Id, string Name, string Description)
{
    /// <summary>The upgrade card icons on disk are <c>icon_&lt;id&gt;.png</c>.</summary>
    public string IconKey => "icon_" + Id;
}

public static class CardTexts
{
    public static readonly CardText[] All =
    {
${rows}
    };

    /// <summary>The text for a catalog index, or a placeholder if the table has gone stale.</summary>
    public static CardText At(int index) =>
        index >= 0 && index < All.Length ? All[index] : new CardText("", "?", "");

    /// <summary>
    /// Throws if this table and the ported catalog have drifted apart.
    /// </summary>
    /// <remarks>
    /// CHECKED AT STARTUP RATHER THAN IN A TEST, because the test project references the simulation
    /// and not the front-end - and a check that lives where the mistake is made is worth more than
    /// one that lives where it is convenient. A card added to the TypeScript and not regenerated
    /// here would otherwise show up as three cards wearing each other's names, which is the kind of
    /// bug a player reports as "the game lied to me".
    /// </remarks>
    public static void Verify(int catalogCount)
    {
        if (All.Length != catalogCount)
        {
            throw new InvalidOperationException(
                $"CardTexts holds {All.Length} cards but the catalog has {catalogCount}. " +
                "Re-run \`npx tsx tools/gen_card_text.ts\`.");
        }
    }
}
`;

const out = resolve(process.cwd(), 'cs/src/Scrapyard.Game/CardTexts.cs');
writeFileSync(out, src);
console.log(`wrote ${out}  (${UPGRADE_CATALOG.length} cards)`);
