/**
 * GOLDEN FIXTURE for the ground-cover scatter. Feeds `cs/tests/.../GroundCoverTests.cs`.
 *
 * The cover is decoration - it collides with nothing and reaches no part of the world hash - so a
 * wrong scatter cannot break a run. What it CAN do is make the C# build and the web build disagree
 * about what the same seed looks like, which turns "here is a screenshot of the bug" into something
 * nobody can reproduce.
 *
 * Any avalanche function scatters rocks. Only THIS one scatters the same rocks, and it is exactly
 * the kind of code a port gets subtly wrong. Three traps sit in six lines: the FIRST mix below is a
 * plain `*`, which is a float64 multiply whose product passes 2^53 and loses bits before `^` coerces
 * it - the two after it are `Math.imul` and genuinely wrap; and `>>>` is a logical shift. The port
 * fell into the first of those, and only this fixture noticed, because every wrong version still
 * produces a perfectly plausible yard. So the placement decision for a fixed set of cells is
 * recorded here and compared bit for bit.
 *
 * Large seeds are deliberate: at small seeds a float64 multiply and an imul agree, so a fixture of
 * tidy little numbers would have passed against the broken port.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const OUT_PATH = resolve(process.cwd(), 'goldens/ground-cover-fixture.json');

// ---------------------------------------------------------------------------------------------
// Transcribed from src/render/groundCover.ts. Kept in step by the C# test failing when it is not.
// ---------------------------------------------------------------------------------------------

const CELL = 190;
const CLEAR_CELLS = 3;
const OCCUPANCY = 0.62;
const MIN_SIZE = 16;
const MAX_SIZE = 38;
const VARIANTS = 8;

function hash(x: number, y: number, seed: number): number {
  let h = (x * 0x1f1f1f1f) ^ (y * 0x8da6b343) ^ (seed * 0xd8163841);
  h = Math.imul(h ^ (h >>> 15), 0x2c1b3c6d);
  h = Math.imul(h ^ (h >>> 12), 0x297a2d39);
  h ^= h >>> 15;
  return h >>> 0;
}

function unit(h: number, k: number): number {
  return (((h >>> (k * 5)) ^ (h << (k * 3))) >>> 8) / 0x1000000;
}

const scratch = new Float64Array(1);
const bits = new Uint32Array(scratch.buffer);
function f64(v: number): string {
  scratch[0] = v;
  return bits[1].toString(16).padStart(8, '0') + bits[0].toString(16).padStart(8, '0');
}

// ---------------------------------------------------------------------------------------------

const SEEDS = [0, 1, 1554094637, -1030298724, 0x5ca19a2d];

const cells: unknown[] = [];
for (const seed of SEEDS) {
  // A band that crosses the cleared centre, so the skip rule is exercised alongside the scatter,
  // and reaches negative coordinates, where a sign-extending shift would diverge.
  for (let cy = -5; cy <= 5; cy++) {
    for (let cx = -5; cx <= 5; cx++) {
      const h = hash(cx, cy, seed);
      const cleared = Math.abs(cx) <= CLEAR_CELLS && Math.abs(cy) <= CLEAR_CELLS;
      const empty = unit(h, 0) >= OCCUPANCY;
      cells.push({
        seed,
        cx,
        cy,
        hash: h >>> 0,
        cleared,
        empty,
        x: f64(cx * CELL + unit(h, 1) * CELL),
        y: f64(cy * CELL + unit(h, 2) * CELL),
        size: f64(MIN_SIZE + unit(h, 3) * (MAX_SIZE - MIN_SIZE)),
        variant: h % VARIANTS,
        quarterTurns: Math.floor(unit(h, 4) * 4),
        mirrored: unit(h, 5) < 0.5,
      });
    }
  }
}

const fixture = {
  note: 'Generated by tools/ground_cover_fixture.ts. Do not edit by hand.',
  cell: CELL,
  clearCells: CLEAR_CELLS,
  occupancy: f64(OCCUPANCY),
  minSize: f64(MIN_SIZE),
  maxSize: f64(MAX_SIZE),
  variants: VARIANTS,
  cells,
};

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, `${JSON.stringify(fixture)}\n`);
console.log(`wrote ${OUT_PATH}  (${cells.length} cells over ${SEEDS.length} seeds)`);
