#!/usr/bin/env node
/**
 * prepare_assets.mjs - copy the sprites the game ACTUALLY uses out of assets/kenney/** into
 * public/sprites/, under flat, lowercase, space-free names, and generate the PWA icons.
 *
 * WHY THIS EXISTS
 * ---------------
 * The four Kenney packs total 1090 files. Shipping them all would put ~85 MB of decoded texture
 * memory and 1090 service-worker cache entries on a phone (docs/ASSET_MANIFEST.md §5.2). This
 * script copies exactly 71 files - the ones docs/ASSET_MANIFEST.md §7 names - and nothing else.
 *
 * SOURCE PATHS CONTAIN SPACES AND PARENTHESES (`Top view`, `Default size`, `PNG (Transparent)`).
 * They are handled here as JS strings, never as shell words, and they never reach the browser:
 * every destination name is flat and URL-safe.
 *
 * IDEMPOTENT. Re-running copies nothing when the destination already matches the source byte
 * length and is no older than it. `--force` copies regardless.
 *
 * NOT DONE HERE, DELIBERATELY:
 *   - No downscaling of the 512x512 particles. That needs an image codec and this repo has no
 *     image dependency. The five particles we ship are 328 KB on disk and ~5 MB of VRAM, which is
 *     inside budget; the manifest's ~85 MB figure is for loading all 81 particles, which we do
 *     not. If a particle downscale is ever wanted it belongs in the atlas packer, not here.
 *   - No atlas packing. docs/ASSET_MANIFEST.md §6 recommends one packed 1024x1024 atlas and
 *     package.json already reserves `npm run assets` -> tools/pack-assets.mjs for it. Until that
 *     lands the renderer loads individual textures; see README "What's next".
 *
 * Usage:
 *   node tools/prepare_assets.mjs [--force] [--quiet]
 */

import { deflateSync } from 'node:zlib';
import { mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC_ROOT = join(ROOT, 'assets', 'kenney');
const OUT_SPRITES = join(ROOT, 'public', 'sprites');
const OUT_ICONS = join(ROOT, 'public', 'icons');

const FORCE = process.argv.includes('--force');
const QUIET = process.argv.includes('--quiet');

// ---------------------------------------------------------------------------------------------
// The manifest. Left column is relative to assets/kenney/, right column is the frame key the
// renderer asks for (src/render/assets.ts) and the file name under public/sprites/.
// ---------------------------------------------------------------------------------------------

/** @type {Array<[string, string]>} */
const COPIES = [];

// -- 1. NO PLAYER MECHS HERE. The eight chassis and the turret are GENERATED by
//       tools/make-mechs.mjs (`npm run mechs`), not copied from a pack: robot-pack's top view is
//       a slab on treads, which is a tank. ASSET_MANIFEST §1. This file used to copy them, and
//       re-adding that loop would quietly resurrect the old art alongside the new. ------------

// -- 2. All 48 enemies, RETINA (128x128). ASSET_MANIFEST §2 + gotcha 6: the Default size art is
//       a 3.3x upscale for swarmers on a DPR-3 screen; Retina cuts it to 1.6x. -----------------
for (let n = 1; n <= 48; n++) {
  const nn = String(n).padStart(2, '0');
  COPIES.push([`sci-fi-rts/PNG/Retina/Unit/scifiUnit_${nn}.png`, `enemy_${nn}.png`]);
}

// -- 3. Ground tile. Stays a standalone 64x64 power-of-two texture so WebGL REPEAT works;
//       a sub-rect of an atlas cannot wrap (ASSET_MANIFEST gotcha 8). ---------------------------
COPIES.push(['sci-fi-rts/PNG/Default size/Tile/scifiTile_42.png', 'floor.png']);

// -- 4. Shell and gem. ASSET_MANIFEST §3.2 / §3.5 ----------------------------------------------
COPIES.push(['space-shooter-extension/PNG/Sprites/Missiles/spaceMissiles_012.png', 'shell.png']);
// The missile racks draw a different projectile from the Cannon's shell - a longer finned body,
// so a screen carrying both reads as two weapons rather than one firing oddly.
COPIES.push(['space-shooter-extension/PNG/Sprites/Missiles/spaceMissiles_001.png', 'missile.png']);
// Machine gun rounds: a small slug, distinct from both the Cannon's shell and the missile body.
COPIES.push(['space-shooter-extension/PNG/Sprites/Missiles/spaceMissiles_027.png', 'slug.png']);
COPIES.push(['space-shooter-extension/PNG/Sprites/Parts/spaceParts_035.png', 'gem.png']);

// -- 5. Death puff, 7 frames. Strictly size-monotonic subset: 011 and 014 are deliberately
//       excluded because they break the ordering and the puff would pop inward. §3.4 -----------
const PUFF_FRAMES = ['008', '009', '010', '012', '013', '015', '016'];
PUFF_FRAMES.forEach((frame, i) => {
  COPIES.push([`space-shooter-extension/PNG/Sprites/Effects/spaceEffects_${frame}.png`, `puff_${i}.png`]);
});

// -- 6. The five particles we actually draw. All 512x512, all premultiplied alpha, all drawn
//       with blendMode 'add' which consumes RGB directly (gotcha 3). ---------------------------
COPIES.push(['particle-pack/PNG (Transparent)/muzzle_04.png', 'fx_muzzle.png']);
COPIES.push(['particle-pack/PNG (Transparent)/light_03.png', 'fx_flash.png']);
COPIES.push(['particle-pack/PNG (Transparent)/fire_01.png', 'fx_burst.png']);
COPIES.push(['particle-pack/PNG (Transparent)/star_08.png', 'fx_sparkle.png']);
COPIES.push(['particle-pack/PNG (Transparent)/trace_07.png', 'fx_trail.png']);

// ---------------------------------------------------------------------------------------------
// Copy
// ---------------------------------------------------------------------------------------------

function log(...args) {
  if (!QUIET) console.log(...args);
}

/** @returns {{ copied: number, skipped: number, bytes: number }} */
function copyAll() {
  mkdirSync(OUT_SPRITES, { recursive: true });

  const missing = [];
  for (const [src] of COPIES) {
    try {
      statSync(join(SRC_ROOT, src));
    } catch {
      missing.push(src);
    }
  }
  if (missing.length > 0) {
    console.error(`prepare_assets: ${missing.length} source file(s) missing under ${SRC_ROOT}:`);
    for (const m of missing) console.error(`  ${m}`);
    process.exit(1);
  }

  let copied = 0;
  let skipped = 0;
  let bytes = 0;

  for (const [src, dest] of COPIES) {
    const from = join(SRC_ROOT, src);
    const to = join(OUT_SPRITES, dest);
    const s = statSync(from);
    bytes += s.size;

    if (!FORCE) {
      let d = null;
      try {
        d = statSync(to);
      } catch {
        /* not there yet */
      }
      if (d !== null && d.size === s.size && d.mtimeMs >= s.mtimeMs) {
        skipped++;
        continue;
      }
    }

    writeFileSync(to, readFileSync(from));
    copied++;
  }

  return { copied, skipped, bytes };
}

// ---------------------------------------------------------------------------------------------
// PWA icons
//
// Generated rather than committed as opaque binaries so the art is reviewable as code and a
// palette change is a one-line diff. A minimal PNG encoder is ~30 lines on top of node:zlib,
// which is cheaper than taking an image dependency for four flat-colour squares.
//
// iOS masks the corners of apple-touch-icon itself, so the source must be SQUARE and FULLY
// OPAQUE with the art inset (docs/IPHONE_PLATFORM.md §3.3). The maskable variant insets further:
// the maskable safe zone is the centre circle of 80% diameter, so art stays inside ~60%.
// ---------------------------------------------------------------------------------------------

const PALETTE = {
  // The icon is painted from the GAME's own colours, not from a separate icon palette. `bg` is
  // the dark the manifest and the theme-color meta tag already declare, so the launch splash and
  // the tab chrome agree with the artwork; `floor` is the rust the arena is tiled with; `hull`,
  // `trim` and `glass` are lifted verbatim from Slate's row in tools/make-mechs.mjs, which is the
  // chassis the picker opens on.
  bg: [0x0b, 0x0e, 0x13],
  floor: [0xa8, 0x54, 0x33],
  floorDark: [0x8f, 0x45, 0x29],
  hull: [0x8d, 0x99, 0xae],
  trim: [0x5b, 0x67, 0x79],
  metal: [0x39, 0x44, 0x52],
  glass: [0x4f, 0xa8, 0xff],
  // The Energy Shield's rim, the same 0x4fa8ff the renderer draws - and the reason the icon reads
  // as THIS game rather than as a generic top-down shooter.
  shield: [0x4f, 0xa8, 0xff],
};

class Raster {
  constructor(size) {
    this.size = size;
    this.px = new Uint8Array(size * size * 4);
  }

  /** Solid fill of the whole canvas - keeps the icon opaque, which iOS requires. */
  clear(rgb) {
    const { px } = this;
    for (let i = 0; i < px.length; i += 4) {
      px[i] = rgb[0];
      px[i + 1] = rgb[1];
      px[i + 2] = rgb[2];
      px[i + 3] = 255;
    }
  }

  /** Coordinates are fractions of the canvas, so one description serves every icon size. */
  rect(x0, y0, x1, y1, rgb, radius = 0) {
    const s = this.size;
    const ax = Math.round(x0 * s);
    const ay = Math.round(y0 * s);
    const bx = Math.round(x1 * s);
    const by = Math.round(y1 * s);
    const r = radius * s;
    for (let y = Math.max(0, ay); y < Math.min(s, by); y++) {
      for (let x = Math.max(0, ax); x < Math.min(s, bx); x++) {
        if (r > 0) {
          // Round the corners by testing against the inset corner circles.
          const cx = Math.min(Math.max(x + 0.5, ax + r), bx - r);
          const cy = Math.min(Math.max(y + 0.5, ay + r), by - r);
          const dx = x + 0.5 - cx;
          const dy = y + 0.5 - cy;
          if (dx * dx + dy * dy > r * r) continue;
        }
        const i = (y * s + x) * 4;
        this.px[i] = rgb[0];
        this.px[i + 1] = rgb[1];
        this.px[i + 2] = rgb[2];
        this.px[i + 3] = 255;
      }
    }
  }

  circle(cxf, cyf, rf, rgb) {
    const s = this.size;
    const cx = cxf * s;
    const cy = cyf * s;
    const r = rf * s;
    const r2 = r * r;
    for (let y = Math.max(0, Math.floor(cy - r)); y < Math.min(s, Math.ceil(cy + r)); y++) {
      for (let x = Math.max(0, Math.floor(cx - r)); x < Math.min(s, Math.ceil(cx + r)); x++) {
        const dx = x + 0.5 - cx;
        const dy = y + 0.5 - cy;
        if (dx * dx + dy * dy > r2) continue;
        const i = (y * s + x) * 4;
        this.px[i] = rgb[0];
        this.px[i + 1] = rgb[1];
        this.px[i + 2] = rgb[2];
        this.px[i + 3] = 255;
      }
    }
  }

  /** PNG, colour type 6 (RGBA), bit depth 8, filter 0 on every row. */
  toPng() {
    const s = this.size;
    const stride = s * 4;
    const raw = Buffer.alloc((stride + 1) * s);
    for (let y = 0; y < s; y++) {
      raw[y * (stride + 1)] = 0; // filter: None
      Buffer.from(this.px.buffer, y * stride, stride).copy(raw, y * (stride + 1) + 1);
    }

    const ihdr = Buffer.alloc(13);
    ihdr.writeUInt32BE(s, 0);
    ihdr.writeUInt32BE(s, 4);
    ihdr[8] = 8; // bit depth
    ihdr[9] = 6; // colour type RGBA
    ihdr[10] = 0; // deflate
    ihdr[11] = 0; // adaptive filtering
    ihdr[12] = 0; // no interlace

    return Buffer.concat([
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
      chunk('IHDR', ihdr),
      chunk('IDAT', deflateSync(raw, { level: 9 })),
      chunk('IEND', Buffer.alloc(0)),
    ]);
  }
}

function chunk(type, data) {
  const out = Buffer.alloc(12 + data.length);
  out.writeUInt32BE(data.length, 0);
  out.write(type, 4, 'ascii');
  data.copy(out, 8);
  out.writeUInt32BE(crc32(out.subarray(4, 8 + data.length)) >>> 0, 8 + data.length);
  return out;
}

const CRC_TABLE = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return c ^ -1;
}

/**
 * THE APP ICON: Slate, seen from above inside its Energy Shield, on the arena floor.
 *
 * It is drawn rather than cropped from the sprites because there is no PNG DECODER here - the
 * ~30 lines on top of node:zlib below only encode - and taking an image dependency to composite
 * one 180 px square is a poor trade. Everything is rectangles and circles, which is also what
 * keeps it legible at 32 px in a browser tab.
 *
 * WHAT IT HAS TO SAY, in order, because at 32 px only the first two survive:
 *   1. a blue ring - the shield, and the one shape nothing else in this genre has;
 *   2. a grey machine facing right, with a lit cockpit;
 *   3. rust ground, so it is not another dark square on a home screen full of dark squares.
 *
 * `inset` is the fraction of the canvas left empty around the art. iOS masks the corners of
 * apple-touch-icon itself, so the canvas stays SQUARE and FULLY OPAQUE and the art moves inward.
 */
function drawIcon(size, inset) {
  const r = new Raster(size);
  // Opaque to the very edge: iOS composites nothing behind a home-screen icon, and a transparent
  // corner there is a black corner.
  r.clear(PALETTE.bg);

  const a = inset;
  const b = 1 - inset;
  const w = b - a;
  const at = (u, v) => [a + u * w, a + v * w];
  const cx = a + 0.5 * w;
  const cy = a + 0.5 * w;

  // --- ground -------------------------------------------------------------------------------
  // A rounded rust plate rather than a full bleed, so the maskable variant (which insets much
  // further) still shows the frame instead of one flat colour.
  {
    const [x0, y0] = at(0, 0);
    const [x1, y1] = at(1, 1);
    r.rect(x0, y0, x1, y1, PALETTE.floor, 0.16 * w);
  }
  // Two darker flecks, the same trick the floor tile uses. Enough to stop the plate reading as a
  // solid swatch; not enough to compete with the mech at 32 px.
  {
    const [x0, y0] = at(0.09, 0.13);
    const [x1, y1] = at(0.2, 0.24);
    r.rect(x0, y0, x1, y1, PALETTE.floorDark, 0.02 * w);
    const [x2, y2] = at(0.76, 0.72);
    const [x3, y3] = at(0.89, 0.85);
    r.rect(x2, y2, x3, y3, PALETTE.floorDark, 0.02 * w);
  }

  // --- shield rim ---------------------------------------------------------------------------
  // Drawn as an annulus: the blue disc, then the floor punched back out of its middle. The mech
  // goes on top afterwards, so the punch never eats into it.
  {
    const outer = 0.42 * w;
    r.circle(cx, cy, outer, PALETTE.shield);
    r.circle(cx, cy, outer - 0.035 * w, PALETTE.floor);
  }

  // --- mech, facing +x ------------------------------------------------------------------------
  // Legs first, splayed either side, then the hull over them: the same stacking order the renderer
  // uses, and the reason the machine reads as standing on the ground rather than lying on it.
  for (const [ly0, ly1] of [
    [0.25, 0.35],
    [0.65, 0.75],
  ]) {
    const [x0, y0] = at(0.34, ly0);
    const [x1, y1] = at(0.6, ly1);
    r.rect(x0, y0, x1, y1, PALETTE.metal, 0.03 * w);
  }
  // Shoulder pods, one either side of the hull - Slate's twin gun pods, and the silhouette detail
  // that stops the chassis reading as a plain rounded rectangle.
  for (const [py0, py1] of [
    [0.29, 0.41],
    [0.59, 0.71],
  ]) {
    const [x0, y0] = at(0.43, py0);
    const [x1, y1] = at(0.65, py1);
    r.rect(x0, y0, x1, y1, PALETTE.trim, 0.03 * w);
  }
  // Hull.
  {
    const [x0, y0] = at(0.37, 0.36);
    const [x1, y1] = at(0.66, 0.64);
    r.rect(x0, y0, x1, y1, PALETTE.hull, 0.06 * w);
  }
  // Cockpit, forward on the hull. The one lit thing in the icon, and it is the shield's blue -
  // two uses of one colour reads as deliberate where three colours read as noise.
  {
    const [x0, y0] = at(0.54, 0.43);
    const [x1, y1] = at(0.65, 0.57);
    r.rect(x0, y0, x1, y1, PALETTE.glass, 0.04 * w);
  }
  // Barrels, pointing +x, breaking the rim - the machine is bigger than the field around it.
  for (const [by0, by1] of [
    [0.44, 0.475],
    [0.525, 0.56],
  ]) {
    const [x0, y0] = at(0.66, by0);
    const [x1, y1] = at(0.92, by1);
    r.rect(x0, y0, x1, y1, PALETTE.metal, 0.015 * w);
  }

  return r.toPng();
}

function writeIcons() {
  mkdirSync(OUT_ICONS, { recursive: true });
  /** @type {Array<[string, number, number]>} name, size, inset */
  const icons = [
    // THE icon iOS actually uses. Square, opaque, art inset ~10% - iOS masks the corners itself.
    ['apple-touch-icon-180.png', 180, 0.1],
    ['icon-192.png', 192, 0.1],
    ['icon-512.png', 512, 0.1],
    // Maskable safe zone is the centre circle of 80% diameter, so the art insets further.
    ['icon-maskable-512.png', 512, 0.22],
    // Browser tab / bookmark.
    ['favicon-32.png', 32, 0.06],
  ];
  let bytes = 0;
  for (const [name, size, inset] of icons) {
    const png = drawIcon(size, inset);
    writeFileSync(join(OUT_ICONS, name), png);
    bytes += png.length;
  }
  return { count: icons.length, bytes };
}

// ---------------------------------------------------------------------------------------------

const t0 = Date.now();
const sprites = copyAll();
const icons = writeIcons();

log(
  `prepare_assets: ${COPIES.length} sprites (${sprites.copied} copied, ${sprites.skipped} up to date, ` +
    `${(sprites.bytes / 1024).toFixed(0)} KB) -> public/sprites/`,
);
log(`prepare_assets: ${icons.count} icons (${(icons.bytes / 1024).toFixed(0)} KB) -> public/icons/`);
log(`prepare_assets: done in ${Date.now() - t0} ms`);
