namespace Scrapyard.Game;

/// <summary>
/// What a card SAYS - its id on disk, its name, and its one line of text.
/// </summary>
/// <remarks>
/// <para>
/// NOT IN <c>Scrapyard.Core</c>, because none of it changes what happens. The simulation knows a
/// card by an integer and by its effects; the words are the player's half of the contract, and they
/// live with the thing that draws them.
/// </para>
/// <para>
/// GENERATED by <c>tools/gen_card_text.ts</c> from <c>src/core/data/upgrades.ts</c> rather than
/// retyped, because retyping 21 descriptions into another language is how three cards end up
/// mislabelled. THE ORDER IS THE FORMAT: index i here is catalog index i there, and
/// <see cref="CardTexts.Verify"/> refuses to start if the two have drifted apart.
/// </para>
/// <para>
/// NO MAGNITUDES, and that rule belongs to the text rather than to this file: a card is read in
/// four seconds with a horde closing in, and "+7% range" invites arithmetic where "every weapon
/// reaches further" invites a decision. Counts of projectiles DO appear, because a third missile is
/// a different thing happening rather than a bigger number.
/// </para>
/// </remarks>
public readonly record struct CardText(string Id, string Name, string Description)
{
    /// <summary>The upgrade card icons on disk are <c>icon_&lt;id&gt;.png</c>.</summary>
    public string IconKey => "icon_" + Id;
}

public static class CardTexts
{
    public static readonly CardText[] All =
    {
        new("w-cannon", "Cannon", "Lobs a heavy shell at the highest-HP enemy in range. One target, hit hard."),
        new("w-missile-short", "Short Missiles", "Two homing missiles fired where you last moved. Slow to rearm, hits hard."),
        new("w-missile-long", "Long Missiles", "Three missiles on a long fuse, fired where you last moved. Weak homing, wide reach."),
        new("w-machine-gun", "Machine Gun", "Two rounds at a time into the weakest enemy, very close in. A deep belt, then a long reload."),
        new("w-flak-cannon", "Flak Cannon", "Three shells a burst into a wide, random spray at the nearest enemy - far-reaching and wildly inaccurate. A deep magazine, then a long reload."),
        new("w-artillery", "Heavy Artillery", "Two shells fall on random ground nearby after a short fuse. Aims at nothing. Big blast."),
        new("w-drone", "Drones", "Builds a drone that flies escort, hunts anything that comes close, and shoots it with a machine gun until its magazine is dry. Then it detonates."),
        new("w-phase-cannon", "Phase Cannon", "One plasma bolt that flies through everything - the horde, the wrecks, the walls - and bursts on the thickest knot of enemies it can find."),
        new("w-laser-short", "Short Laser", "Green beam. Burns whatever stands between you and the weakest enemy."),
        new("w-laser-medium", "Medium Laser", "Blue beam. Moderate damage at middling range, and it runs hot."),
        new("w-laser-long", "Long Laser", "Red beam. Heavy damage at long range, in short bursts."),
        new("p-range", "Targeting Optics", "Every weapon reaches further."),
        new("p-damage", "Ordnance", "Every weapon hits harder. A hotter-running laser burns through its heat faster."),
        new("p-rate", "Feed Systems", "Every weapon fires more often - shorter cooldowns, faster heat dispersion, a quicker reload."),
        new("p-speed", "Servo Drive", "The chassis moves faster."),
        new("p-armour", "Ablative Plate", "Takes something off every hit you take - never all of it, and never nothing."),
        new("p-repair", "Field Repair", "A repair clock. Every few seconds it puts a little of your hull back - the only thing in the yard that mends you without being picked up."),
        new("p-shield", "Energy Shield", "A blue rim absorbs one hit outright and burns whatever broke it. A moment of immunity with it, and then it comes back."),
        new("p-radiator", "Radiator Bank", "Every beam runs a bigger heat buffer and sheds it faster between bursts."),
        new("p-blast", "Shaped Charges", "Every blast reaches wider."),
        new("p-ammo", "Ammo Drums", "Every magazine on the chassis carries more rounds."),
    };

    /// <summary>The text for a catalog index, or a placeholder if the table has gone stale.</summary>
    public static CardText At(int index) =>
        index >= 0 && index < All.Length ? All[index] : new CardText("", "?", "");

    /// <summary>
    /// Throws if this table and the ported catalog have drifted apart.
    /// </summary>
    /// <remarks>
    /// CHECKED AT STARTUP RATHER THAN IN A TEST, because the test project references the simulation
    /// and not the front-end - and a check that lives where the mistake is made is worth more than
    /// one that lives where it is convenient. A card added to the TypeScript and not regenerated
    /// here would otherwise show up as three cards wearing each other's names, which is the kind of
    /// bug a player reports as "the game lied to me".
    /// </remarks>
    public static void Verify(int catalogCount)
    {
        if (All.Length != catalogCount)
        {
            throw new InvalidOperationException(
                $"CardTexts holds {All.Length} cards but the catalog has {catalogCount}. " +
                "Re-run `npx tsx tools/gen_card_text.ts`.");
        }
    }
}
