// <auto-generated>
//   Emitted by tools/gen_creature_art.ts from the TypeScript level catalogs.
//   Do not edit: run `npm run creatureart` instead.
// </auto-generated>

#nullable enable

namespace Scrapyard.Game;

/// <summary>
/// Which sprite every creature draws, at what size, and how it carries itself.
/// </summary>
/// <remarks>
/// <para>
/// GENERATED FROM THE TYPESCRIPT CATALOGS, never retyped. <c>Scrapyard.Core</c> knows a
/// creature by an integer and nothing else - what it looks like changes nothing about the
/// fight, so none of it is in the ported simulation. A creature whose second frame was
/// mistyped by hand would draw its healthy sprite forever and nobody would notice, because
/// damage stages are presentation only and the simulation never reads past frame 0.
/// </para>
/// <para>
/// DAMAGE STAGES ARE DRAWN, NEVER SIMULATED. A snail becomes a slug at half health and a
/// hydra sheds a head every fifth of its bar. Putting that in the simulation would add state
/// that must hash, replay and stay deterministic in exchange for nothing at all: a creature
/// with five faces is one enemy, and the sim is entitled to keep thinking so.
/// </para>
/// </remarks>
public static class CreatureArtTable
{
    /// <summary>One creature: its frames healthiest-first, and how wide it is drawn.</summary>
    public readonly record struct Def(string[] Frames, double DrawSize);

    /// <summary>
    /// Largest content dimension of each Kenney enemy hull, in DEFAULT-size pixels.
    /// </summary>
    /// <remarks>
    /// SCRAPYARD ONLY, and MEASURED BY HAND once because the art cannot be trimmed after the
    /// fact. Kenney units sit inside a fixed 64x64 canvas with wildly varying margins - a runt
    /// is 16x24 pixels of art in that canvas - so scaling the canvas would draw a 26-unit runt
    /// as a 6.5-unit speck inside its own 26-unit collision circle. Mossy Mayhem needs no such
    /// table: its bake trims every tile to its opaque bounding box, so the PNG IS the content.
    /// </remarks>
    public static readonly int[] HullContentPx = { 24, 24, 24, 24, 24, 32, 40, 40, 51, 44, 40, 24 };

    /// <summary>The retina art ships at exactly 2x the Default-size canvas AND content.</summary>
    public const int EnemyRetinaFactor = 2;

    /// <summary>Scrapyard's creatures, indexed by <c>typeId</c>.</summary>
    public static readonly Def[] Scrapyard =
    {
        new(new[] { "enemy_01" }, 26),
        new(new[] { "enemy_02" }, 26),
        new(new[] { "enemy_03" }, 26),
        new(new[] { "enemy_04" }, 26),
        new(new[] { "enemy_05" }, 26),
        new(new[] { "enemy_06" }, 34),
        new(new[] { "enemy_07" }, 42),
        new(new[] { "enemy_08" }, 34),
        new(new[] { "enemy_09" }, 52),
        new(new[] { "enemy_10" }, 52),
        new(new[] { "enemy_11" }, 42),
        new(new[] { "enemy_12" }, 26),
        new(new[] { "enemy_13" }, 26),
        new(new[] { "enemy_14" }, 26),
        new(new[] { "enemy_15" }, 26),
        new(new[] { "enemy_16" }, 26),
        new(new[] { "enemy_17" }, 26),
        new(new[] { "enemy_18" }, 34),
        new(new[] { "enemy_19" }, 42),
        new(new[] { "enemy_20" }, 34),
        new(new[] { "enemy_21" }, 52),
        new(new[] { "enemy_22" }, 52),
        new(new[] { "enemy_23" }, 42),
        new(new[] { "enemy_24" }, 26),
        new(new[] { "enemy_25" }, 26),
        new(new[] { "enemy_26" }, 26),
        new(new[] { "enemy_27" }, 26),
        new(new[] { "enemy_28" }, 26),
        new(new[] { "enemy_29" }, 26),
        new(new[] { "enemy_30" }, 34),
        new(new[] { "enemy_31" }, 42),
        new(new[] { "enemy_32" }, 34),
        new(new[] { "enemy_33" }, 52),
        new(new[] { "enemy_34" }, 52),
        new(new[] { "enemy_35" }, 42),
        new(new[] { "enemy_36" }, 26),
        new(new[] { "enemy_37" }, 26),
        new(new[] { "enemy_38" }, 26),
        new(new[] { "enemy_39" }, 26),
        new(new[] { "enemy_40" }, 26),
        new(new[] { "enemy_41" }, 26),
        new(new[] { "enemy_42" }, 34),
        new(new[] { "enemy_43" }, 42),
        new(new[] { "enemy_44" }, 34),
        new(new[] { "enemy_45" }, 52),
        new(new[] { "enemy_46" }, 52),
        new(new[] { "enemy_47" }, 42),
        new(new[] { "enemy_48" }, 26),
    };

    /// <summary>Mossy Mayhem's creatures, indexed by <c>typeId</c>.</summary>
    public static readonly Def[] MossyMayhem =
    {
        new(new[] { "moss_wandering_mushroom" }, 26),
        new(new[] { "moss_giant_blowfly" }, 26),
        new(new[] { "moss_killer_bee" }, 26),
        new(new[] { "moss_giant_mosquito" }, 26),
        new(new[] { "moss_jelly" }, 34),
        new(new[] { "moss_ooze" }, 34),
        new(new[] { "moss_giant_snail", "moss_giant_slug" }, 34),
        new(new[] { "moss_jackal" }, 26),
        new(new[] { "moss_raiju" }, 26),
        new(new[] { "moss_hell_hound" }, 26),
        new(new[] { "moss_vine_stalker" }, 34),
        new(new[] { "moss_draconic_green" }, 42),
        new(new[] { "moss_earth_elemental" }, 34),
        new(new[] { "moss_stone_golem" }, 34),
        new(new[] { "moss_iron_golem" }, 34),
        new(new[] { "moss_dragon" }, 42),
        new(new[] { "moss_golden_dragon" }, 42),
        new(new[] { "moss_hydra_5", "moss_hydra_4", "moss_hydra_3", "moss_hydra_2", "moss_hydra_1" }, 42),
    };

    /// <summary>City Chaos's creatures, indexed by <c>typeId</c>.</summary>
    public static readonly Def[] CityChaos =
    {
        new(new[] { "city_robot" }, 26),
        new(new[] { "city_2legs" }, 26),
        new(new[] { "city_flying" }, 26),
        new(new[] { "city_rover" }, 34),
        new(new[] { "city_2legs_gun" }, 34),
        new(new[] { "city_flying_gun" }, 34),
        new(new[] { "city_fighter" }, 34),
        new(new[] { "city_tank" }, 42),
        new(new[] { "city_cyb_large" }, 26),
        new(new[] { "city_george" }, 26),
        new(new[] { "city_leela" }, 26),
        new(new[] { "city_stan" }, 26),
        new(new[] { "city_stan" }, 34),
        new(new[] { "city_mike" }, 34),
        new(new[] { "city_bee" }, 34),
        new(new[] { "city_flamingo" }, 34),
        new(new[] { "city_frog" }, 34),
        new(new[] { "city_frog" }, 42),
        new(new[] { "city_panda" }, 42),
    };

    /// <summary>A level's creature table, by the id the simulation carries.</summary>
    /// <remarks>
    /// A LEVEL WITH NO ENTRY GETS AN EMPTY TABLE RATHER THAN A THROW, and the draw path falls
    /// back to the archetype size. City Chaos ships no creatures of its own yet; a run there
    /// should look plain, not crash.
    /// </remarks>
    public static Def[] ForLevel(string levelId) => levelId switch
    {
        "scrapyard" => Scrapyard,
        "mossy-mayhem" => MossyMayhem,
        "city-chaos" => CityChaos,
        _ => System.Array.Empty<Def>(),
    };

    /// <summary>
    /// WHICH WAY A LEVEL'S ART IS DRAWN FACING: 1 for east, -1 for west.
    /// </summary>
    /// <remarks>
    /// The renderer mirrors a creature so it faces the way it is walking, and to do that it has
    /// to know which way the art faces to begin with. That is a fact about the PACK rather than
    /// about the creature - Kenney's RTS units face east, Dungeon Crawl's monster tiles face
    /// west, all 23 of them checked rather than sampled. It was ASSUMED rather than asked once,
    /// and every creature on the moss walked backwards in both directions.
    /// </remarks>
    public static int FacingOf(string levelId) => levelId switch
    {
        "scrapyard" => 1,
        "mossy-mayhem" => -1,
        "city-chaos" => 1,
        _ => 1,
    };

    /// <summary>The sprite drawing a creature's boss rim, or null to reuse the body.</summary>
    /// <remarks>
    /// A TINT IS A MULTIPLY: it can darken a pixel and never brighten one, so a scaled-up copy
    /// only produces a coloured rim if the sprite's OUTER EDGE is bright. Kenney's units are
    /// flat-shaded with no keyline, so a scaled copy of the body IS the outline. Dungeon Crawl
    /// creatures carry a heavy near-black keyline all the way round - measured at 81% near-black
    /// on the Sporeling and 98% on the jelly - which read as a black shadow, worst on bosses
    /// because the band scales with the body. So Mossy draws a baked rim: the alpha mask grown
    /// two pixels, minus itself, painted flat white.
    /// </remarks>
    public static string? RimKeyFor(string levelId, string frame) => levelId switch
    {
        "scrapyard" => null,
        "mossy-mayhem" => frame + "_rim",
        "city-chaos" => null,
        _ => null,
    };

    /// <summary>Rim scale, as a multiple of the body's. A baked rim is 1 - it is already sized.</summary>
    public static double RimScaleOf(string levelId) => levelId switch
    {
        "scrapyard" => 1.2,
        "mossy-mayhem" => 1,
        "city-chaos" => 1.2,
        _ => 1,
    };

    /// <summary>Sprite keys that animate, and which gait they use. Anything absent stands still.</summary>
    /// <remarks>
    /// KEYED BY SPRITE NAME, not by creature id. A name is content that means the same thing
    /// forever, whereas ids are positional - this table would silently start animating the wrong
    /// creature the day somebody inserted a row above it.
    /// </remarks>
    public static readonly Dictionary<string, int> GaitBySprite = new()
    {
        ["moss_wandering_mushroom"] = 1,
        ["moss_jelly"] = 1,
        ["moss_ooze"] = 1,
        ["moss_vine_stalker"] = 2,
    };

    /// <summary>
    /// The catalog's fingerprint at the moment this file was emitted.
    /// </summary>
    /// <remarks>
    /// A GENERATED FILE THAT NOBODY REGENERATES IS WORSE THAN A HAND-WRITTEN ONE, because it
    /// looks authoritative. `tools/gen_creature_art.ts` prints this same number; the test
    /// compares them, so editing a creature and forgetting to re-run the generator is a red
    /// test rather than a snail that quietly stopped losing its shell.
    /// </remarks>
    public const uint CatalogDigest = 0x6556265fu;
}
