// <auto-generated>
//   Emitted by tools/gen_pedia_text.ts from the catalogs and the manual.
//   Do not edit: run `npm run pediatext` instead.
// </auto-generated>
#nullable enable

namespace Scrapyard.Game;

/// <summary>The Scrapopedia's text, generated from the catalogs it must never contradict.</summary>
/// <remarks>
/// <para>
/// DESCRIPTIONS AND TIER LADDERS COME FROM THE CATALOG, never from a second copy written here.
/// A card whose wording changes changes the manual with it, and a reordered ladder reorders
/// too - which is the property retyping any of this into C# would quietly undo.
/// </para>
/// <para>
/// THE MANUAL IS THE PART THE CATALOG CANNOT SAY: how a weapon chooses what to shoot, and what
/// that costs. Every weapon in this game picks its target by a DIFFERENT RULE and a level-up
/// card has no room to say so - the Cannon insists on the biggest thing in range while the
/// Machine Gun finishes the smallest, and the missile racks do not aim at all.
/// </para>
/// </remarks>
public static class PediaText
{
    /// <summary>One entry: the card's own words, its ladder, and how it aims.</summary>
    public readonly record struct Entry(
        string Id, string Name, string Kind, string Description, string[] Tiers,
        string Aims, string[] Notes);

    /// <summary>An ascension, which is a page of its own and never a section on its parent.</summary>
    /// <remarks>
    /// A tier 8 renames the gun, redraws its icon and rewrites what it does; folding that into
    /// the parent's page as a footnote would file the most dramatic thing in the game under the
    /// card it stopped being. It is also what keeps the secret - a "Weapons 4/9" counter that
    /// silently became "4/10" would announce it to a player who had found nothing.
    /// </remarks>
    public readonly record struct Ascension(
        string ParentId, string ParentName, string Name, string Description, string Icon,
        string RequiresName);

    public static readonly Entry[] All =
    {
        new("w-cannon", "Cannon", "weapon", "Lobs a heavy shell at the highest-HP enemy in range. One target, hit hard.",
            new[] { "Unlock.", "Reaches further.", "Lays and fires quicker.", "A heavier shell.", "Reaches further again.", "Lays and fires quicker again.", "Shells punch through one extra enemy." },
            "The HIGHEST-HP enemy in range. Not the nearest - the biggest.", new[] { "It commits. The turret swings onto whatever it has chosen and holds fire until it is laid on, so a target behind you costs shots while the barrel comes round. Watching where the barrel goes is how you know what it has decided.", "The thing with the most hit points is usually at the BACK, behind the chaff that is actually biting you. That is the whole geometry of the weapon: the shell travels through the crowd to reach it, which is why punching through an extra body matters so much once it can.", "One heavy shell at a time, and it shoves what it hits. Nothing else in the yard moves a body the way this does." }),
        new("w-missile-short", "Short Missiles", "weapon", "Two homing missiles fired where you last moved. Slow to rearm, hits hard.",
            new[] { "Unlock.", "Rearms sooner.", "Homes more tightly.", "Heavier warheads.", "Rearms sooner again.", "Homes more tightly again.", "A third missile." },
            "NOTHING. The rack fires along the direction you last MOVED.", new[] { "This is the weapon that makes running a decision. It has no turret and picks no target - the volley leaves along your own heading, so kiting backwards means firing backwards, and turning to face something is how you aim it.", "Once away, each missile steers weakly toward whatever body happens to be nearest to ITSELF, re-judged the whole way. So they fan out and find their own victims rather than converging on one.", "Two warheads at a time, slow to rearm, and each one hits hard enough to matter." }),
        new("w-missile-long", "Long Missiles", "weapon", "Three missiles on a long fuse, fired where you last moved. Weak homing, wide reach.",
            new[] { "Unlock.", "Rearms sooner.", "Homes more tightly.", "Heavier warheads.", "A fourth missile.", "A longer fuse, so they fly further before they fall.", "A fifth missile." },
            "NOTHING. The rack fires along the direction you last MOVED.", new[] { "Same rule as the short rack: no turret, no target, the volley goes where you were going. Turning to face something is how you aim it.", "Weaker homing than the short rack and a much longer fuse, so these travel a long way before they come down. They are the rack you fire into ground you have not reached yet.", "Three missiles to start with, and a finished rack throws five." }),
        new("w-machine-gun", "Machine Gun", "weapon", "Two rounds at a time into the weakest enemy, very close in. A deep belt, then a long reload.",
            new[] { "Unlock.", "A harder-hitting round.", "Spins faster.", "A deeper magazine.", "Reaches further.", "A much harder-hitting round.", "Reloads much faster." },
            "The WEAKEST enemy in range, very close in.", new[] { "The shortest reach of any weapon here. It only does anything at all when you are inside the crowd, which is exactly where its magazine is most likely to run dry.", "A magazine is the third kind of limiter in the game and the one that hurts. A cooldown paces you evenly and heat trades burst against silence every few seconds; a belt gives you a long uninterrupted stream and then takes the weapon away entirely. Every round is a slice of that silence you have already bought.", "It fires two rounds at a time at the lowest-HP body it can see, which makes it a finisher - it cleans up what the heavier guns leave standing." }),
        new("w-flak-cannon", "Flak Cannon", "weapon", "Three shells a burst into a wide, random spray at the nearest enemy - far-reaching and wildly inaccurate. A deep magazine, then a long reload.",
            new[] { "Unlock.", "A harder-hitting shell.", "Fires faster.", "A deeper magazine.", "Reaches further.", "A much harder-hitting shell.", "Reloads much faster." },
            "The NEAREST enemy - and then sprays past it.", new[] { "Three shells a burst, each one thrown down its own randomly drawn line inside a wide cone. It is the only weapon here that cannot be aimed: two bursts at the same body are never the same shape, and no tier narrows the spread.", "It reaches further than any other shell in the game and hits almost nothing at that distance. What it is really firing at is the GROUND BEHIND its target - it shoots the nearest body so the cone opens into whatever is walking up behind it, which is why a wave eats a whole burst and a single straggler eats one shell of it.", "It shares the Machine Gunu2019s mount, and the two can never be carried together. A run picks the stream or the spray.", "Vermilion throws a fourth shell every burst u2014 a denser spray out of the same belt, which empties that much sooner for it.", "A magazine, like the belt gun: a long stretch of fire and then a long silence you have already paid for." }),
        new("w-artillery", "Heavy Artillery", "weapon", "Two shells fall on random ground nearby after a short fuse. Aims at nothing. Big blast.",
            new[] { "Unlock.", "A wider blast.", "Shells fall more often.", "Heavier shells.", "A wider blast again.", "Shells fall more often again.", "A third shell." },
            "NOTHING AT ALL. Shells fall on random ground near you.", new[] { "It is the only weapon that never consults the horde. It does not pick a target, it does not need one, and it will happily bombard an empty yard. Think of it as weather you fight underneath rather than a gun you fire.", "Shells land in a ring of ground around you - past the bodies actually touching you, onto the ground the next wave is crossing. You cannot aim it, but you can decide where you are standing when it lands.", "THE FUSE IS THE WEAPON. A marker sits on the ground before each shell arrives, which is time enough to read it and choose whether to walk into that circle or away from it. The blast is strongest at the centre and weakest at the rim." }),
        new("w-drone", "Drones", "weapon", "Builds a drone that flies escort, hunts anything that comes close, and shoots it with a machine gun until its magazine is dry. Then it detonates.",
            new[] { "Unlock.", "Builds faster.", "A second drone.", "Builds faster again.", "A third drone.", "Builds faster again.", "A fourth drone, and faster still." },
            "The BAY aims at nothing. Each DRONE picks the nearest thing to ITSELF.", new[] { "It is a factory, not a gun. Every thirty seconds it finishes a drone, and the drone does the rest - so the card does nothing at all for the first half minute you hold it.", "A drone flies escort until something comes within twice its reach, then goes and circles THAT and empties a machine gun into it. When the target dies it comes home, picking up anything it passes on the way. It hunts from where it is STANDING, not from where you are, so a drone already out on a kill will chain across a crowd without ever coming back.", "It will not chain forever, though. Nothing more than about two screens from YOU is a target, however close it happens to be to the drone - so a spread-out wave cannot walk your drones off the edge of the fight.", "ITS MAGAZINE IS ITS LIFE. There is no reloading - when the last round is gone it detonates, and the blast is worth about as much as one artillery shell. A drone is a thing you spend, not a thing you keep.", "Finish the bay and four fly at once. It also keeps building at full strength: one finished drone is held in reserve, so a loss is replaced the instant it happens." }),
        new("w-phase-cannon", "Phase Cannon", "weapon", "One plasma bolt that flies through everything - the horde, the wrecks, the walls - and bursts on the thickest knot of enemies it can find.",
            new[] { "Unlock.", "A heavier bolt.", "A wider burst.", "Rearms sooner.", "A heavier bolt again.", "A wider burst again.", "Rearms sooner still." },
            "The enemy with the DENSEST CROWD packed around it - even one behind a wall.", new[] { "The bolt is untouchable in flight. It passes through every enemy, wreck and wall between you and its mark, lands on that one body, and bursts into everything standing around it. Nothing on the way in is hit; the crowd at the arrival point is.", "It is the only gun in the game that does not care about line of sight. Every other weapon refuses or wastes a shot at something behind cover; this one picks the knot of bodies on the far side of the rock wall and reaches it.", "The catch is the turret: the slowest slew in the yard. The bolt cannot miss once fired, so the fight is getting the barrel around in time - a crowd forming behind you is seconds of traverse away, and where you stand decides how much of that you pay." }),
        new("w-laser-short", "Short Laser", "weapon", "Green beam. Burns whatever stands between you and the weakest enemy.",
            new[] { "Unlock.", "Burns hotter - and heats itself up faster doing it.", "A bigger heat sink: longer bursts before it cuts out.", "Sheds heat faster, so it comes back sooner.", "Burns hotter - and heats itself up faster doing it.", "A bigger heat sink: longer bursts before it cuts out.", "Sheds heat faster, so it comes back sooner." },
            "The WEAKEST enemy in range - it finishes rather than starts.", new[] { "A beam burns continuously into one body until that body dies or leaves. There is no shot to miss and no travel time; if the line is clear, the damage is already landing.", "Scrap blocks it. A beam refuses a shot it cannot make cleanly rather than firing into a wreck, which also means it is not paying heat for nothing.", "The shortest reach of the four, so it only works if you are willing to be close." }),
        new("w-laser-medium", "Medium Laser", "weapon", "Blue beam. Moderate damage at middling range, and it runs hot.",
            new[] { "Unlock.", "Burns hotter - and heats itself up faster doing it.", "A bigger heat sink: longer bursts before it cuts out.", "Sheds heat faster, so it comes back sooner.", "Burns hotter - and heats itself up faster doing it.", "A bigger heat sink: longer bursts before it cuts out.", "Sheds heat faster, so it comes back sooner." },
            "The WEAKEST enemy in range - it finishes rather than starts.", new[] { "A beam burns continuously into one body until that body dies or leaves. There is no shot to miss and no travel time; if the line is clear, the damage is already landing.", "Scrap blocks it, and it runs hot for what it does. Heat is the whole limiter on every laser: fire until it cuts out, then wait while it sheds.", "The middle of the three: reaches further than the short laser, cools better than the long one, and is the beam you take if you do not want to build the run around it." }),
        new("w-laser-long", "Long Laser", "weapon", "Red beam. Heavy damage at long range, in short bursts.",
            new[] { "Unlock.", "Burns hotter - and heats itself up faster doing it.", "A bigger heat sink: longer bursts before it cuts out.", "Sheds heat faster, so it comes back sooner.", "Burns hotter - and heats itself up faster doing it.", "A bigger heat sink: longer bursts before it cuts out.", "Sheds heat faster, so it comes back sooner." },
            "The WEAKEST enemy in range - it finishes rather than starts.", new[] { "A beam burns continuously into one body until that body dies or leaves. There is no shot to miss and no travel time; if the line is clear, the damage is already landing.", "The longest reach in the game, and the steepest heat bill to go with it. It fires in short bursts and spends most of a fight cooling, so what it is really buying you is the right to pick a target from a long way off.", "Scrap blocks it, and at this range there is a lot of scrap between you and the far end of the beam." }),
        new("p-range", "Targeting Optics", "passive", "Every weapon reaches further.",
            new[] { "Every weapon reaches a little further.", "Every weapon reaches a little further.", "Every weapon reaches further.", "Every weapon reaches further.", "Every weapon reaches further.", "Every weapon reaches much further.", "Every weapon reaches much further." },
            "Every weapon reaches further.", new[] { "Reach decides what a weapon can even consider shooting, so this is worth most to the guns that are starved of targets and least to the ones already swimming in them.", "It does nothing for the missile racks, which fire whether or not anything is in range - but it is worth a great deal to a short-ranged gun that spends its life waiting for something to walk into it." }),
        new("p-damage", "Ordnance", "passive", "Every weapon hits harder. A hotter-running laser burns through its heat faster.",
            new[] { "Every weapon hits a little harder.", "Every weapon hits a little harder.", "Every weapon hits harder.", "Every weapon hits harder.", "Every weapon hits harder.", "Every weapon hits much harder.", "Every weapon hits much harder." },
            "Every weapon hits harder.", new[] { "The straightforward one, and it applies to everything you are holding at once.", "It costs the lasers something. Raw power on a beam runs it hotter - that is the trade the whole laser ladder is built around - so this makes them hit harder and cut out sooner. Capacity and dispersion are how you buy that back." }),
        new("p-rate", "Feed Systems", "passive", "Every weapon fires more often - shorter cooldowns, faster heat dispersion, a quicker reload.",
            new[] { "Everything fires a little more often, and reloads a little sooner.", "Everything fires a little more often, and reloads a little sooner.", "Everything fires more often, and reloads sooner.", "Everything fires more often, and reloads sooner.", "Everything fires more often, and reloads sooner.", "Everything fires much more often, and reloads much sooner.", "Everything fires much more often, and reloads much sooner." },
            "Everything fires more often.", new[] { "Three limiters, three effects: shorter cooldowns for the guns, faster heat dispersion for the beams, and a quicker reload for anything with a magazine. Whatever you are holding, some part of this card is doing something.", "Careful with a magazine weapon: firing faster empties a belt sooner, so the rate on its own gives back in silence what it bought in burst. The reload half is what actually makes it worth taking there." }),
        new("p-speed", "Servo Drive", "passive", "The chassis moves faster.",
            new[] { "The chassis moves a little faster.", "The chassis moves a little faster.", "The chassis moves faster.", "The chassis moves faster.", "The chassis moves faster.", "The chassis moves much faster.", "The chassis moves much faster." },
            "The chassis moves faster.", new[] { "It raises how fast you can go AND how fast you get there, so the mech feels the same and is simply quicker. A higher top speed on its own would just make it float.", "Everything in this game is downstream of being able to leave: the horde is escapable by walking, gems have to be walked onto, and the missile racks fire wherever you are heading." }),
        new("p-armour", "Ablative Plate", "passive", "Takes something off every hit you take - never all of it, and never nothing.",
            new[] { "A little more plating.", "A little more plating.", "More plating.", "More plating.", "Much more plating.", "Much more plating.", "Much more plating." },
            "Takes something off every hit you take.", new[] { "A flat subtraction, so it is worth the same against a nibble and against a slam - which means it is worth EVERYTHING against a swarm of small things and very little against one big one.", "It can never absorb a hit completely. Something always gets through." }),
        new("p-repair", "Field Repair", "passive", "A repair clock. Every few seconds it puts a little of your hull back - the only thing in the yard that mends you without being picked up.",
            new[] { "Unlock.", "Repairs more each time.", "Repairs more each time.", "Repairs sooner.", "Repairs more each time.", "Repairs more each time.", "Repairs sooner again." },
            "A clock that mends you, slowly, without being asked.", new[] { "Every few seconds it puts a little of the hull back. It is not much at once and it is not meant to be - what it changes is that being hurt is no longer permanent between barrels.", "Half the ladder makes each repair bigger and half makes it come round sooner, which are different things: more is worth having when a repair lands, sooner is worth having while you are still being chased.", "It only mends what is missing. At full hull the clock sits at the top of its dial, so the first repair after a hit is always a whole interval away rather than arriving because the timer happened to be due." }),
        new("p-shield", "Energy Shield", "passive", "A blue rim absorbs one hit outright and burns whatever broke it. A moment of immunity with it, and then it comes back.",
            new[] { "Unlock.", "Comes back sooner.", "A longer moment of immunity when it breaks.", "Comes back sooner again.", "A longer moment still.", "Comes back much sooner.", "A second rim. Each recharges in turn." },
            "A rim that eats one hit outright, whatever the size of it.", new[] { "The opposite shape to plating. Plating shaves a little off everything; a rim stops one hit dead - so it is worth almost nothing against a nibble and everything against the thing that would have killed you.", "Breaking one burns whatever broke it, and buys a moment where nothing can touch you at all. In a crowd that window absorbs the whole simultaneous pile-on rather than the single bite that broke the rim.", "They come back on their own, and a finished shield carries a second rim that recharges in its turn." }),
        new("p-radiator", "Radiator Bank", "passive", "Anything that runs hot carries a bigger heat buffer and sheds it faster between bursts.",
            new[] { "Sheds heat a little faster between bursts.", "Carries a bigger heat buffer.", "Sheds heat faster between bursts.", "Carries a bigger heat buffer.", "Sheds heat faster between bursts.", "Carries a much bigger heat buffer.", "Sheds heat much faster between bursts." },
            "Does nothing at all unless you are holding a laser.", new[] { "A bigger heat buffer and faster shedding between bursts, on every beam you hold. It has no opinion on anything that is not a laser, which is why the deck will not offer it until you already have one.", "Half the ladder buys a longer burst before the cut-out, half buys a shorter wait once it does - which are different things: more buffer is worth having mid-burn, faster shedding is worth having while you wait for it to come back.", "It never touches how hard a beam hits, only how long it can keep hitting. Ordnance is the card for the first half of that trade; this is the card for the second." }),
        new("p-blast", "Shaped Charges", "passive", "Every blast reaches wider.",
            new[] { "Every blast reaches a little wider.", "Every blast reaches a little wider.", "Every blast reaches wider.", "Every blast reaches wider.", "Every blast reaches wider.", "Every blast reaches much wider.", "Every blast reaches much wider." },
            "Does nothing at all unless something you hold explodes.", new[] { "Every blast reaches wider - the artillery barrage, a drone going out, the burst on a phase bolt. Guns that do not explode never notice it, which is why the deck will not offer it until you hold something that does.", "Area grows faster than the ring: widening a circle by half more than doubles the ground it covers. The number on the floor is the radius; the value is the crowd inside it." }),
        new("p-ammo", "Ammo Drums", "passive", "Every magazine on the chassis carries more rounds.",
            new[] { "A little more in every drum.", "A little more in every drum.", "More in every drum.", "More in every drum.", "More in every drum.", "Much more in every drum.", "Much more in every drum." },
            "Does nothing at all unless you are holding a magazine gun.", new[] { "Deeper drums on the belt guns - the Machine Gun and the Flak Cannon, the only two that ever run dry. Everything else in the loadout never notices it, which is why the deck will not offer it until you hold one.", "It never touches the reload itself - that is Feed Systems, and the two stack. This is purely how much fires before the belt runs out at all.", "Locked until proven. It stays out of the deck entirely until a save has spent a long time listening to its own guns click empty and reload." }),
        new("w-mortar", "Mortar", "weapon", "Lobs a heavy shell into the thickest part of the crowd. Prefers whatever is already in front of the barrel.",
            new[] { "Unlock.", "A wider blast.", "Lobs more often.", "A heavier shell.", "A wider blast again.", "Lobs more often again.", "A second shell every volley." },
            "The THICKEST KNOT of enemies inside a cone in front of the barrel.", new[] { "It looks straight ahead first. A narrow cone off the barrel, and if there is a crowd in it that crowd is the target - whatever is happening elsewhere on the field. Only when the cone is empty does it open up, fifteen degrees at a time, until it finds something.", "So it is a gun you AIM WITH THE WHOLE MECH. Point the chassis at the horde and it hammers the horde; turn away and it hunts for the next thing worth a shell. Nothing else in the yard cares which way you are facing except the missile racks, and they only care where you were MOVING.", "The shell is the Heavy Artillery's: the damage is the blast and there is no direct hit worth the name. The difference is that this one is thrown AT something. The barrage does not care where the enemies are, and this does nothing else.", "It shares the Cannon's mount, and the two can never be carried together. A run picks the biggest body or the biggest crowd." }),
        new("w-plasma", "Plasma Thrower", "weapon", "Throws slow gouts of fire and leaves what they touch burning. Picks the biggest thing in front of it that is not already alight.",
            new[] { "Unlock.", "Carries a bigger heat buffer.", "Burns hotter.", "Throws a little further.", "Carries a bigger heat buffer again.", "Sheds heat faster between bursts.", "Burns hotter again." },
            "The BIGGEST enemy in a cone in front of the barrel that is NOT already on fire.", new[] { "It looks straight ahead first, the way the Mortar does - a cone off the barrel, opened thirty degrees at a time until it finds something. So this is the second gun in the yard you aim with the whole mech.", "The bolt is almost nothing. What matters is that whatever it touches CATCHES FIRE, and a burning enemy keeps taking damage for three seconds afterwards. Most of this weapon's damage is never fired.", "Fire does not stack. A second gout into a body already alight only tops the timer back up, which is exactly why the targeting refuses to pick one - left alone the thrower walks itself down a crowd, biggest first, lighting each in turn. If absolutely everything in reach is already burning it shoots the biggest anyway rather than falling silent.", "It runs on HEAT, not a cooldown, and it is not a beam. Held on a target it heats; slewing between them it cools; hold it too long and the breaker trips. A Radiator Bank helps it exactly as much as it helps a laser.", "It shares the Phase Cannon's mount, and the two can never be carried together. A run picks one enormous bolt or a great many small burning ones." }),
        new("w-sludge", "Toxic Sludge", "weapon", "Throws acid out behind the mech, leaving pools that eat whatever walks through them. Only fires when something is back there.",
            new[] { "Unlock.", "The acid bites harder.", "Two more throws before the reload.", "Wider pools.", "The acid bites harder again.", "Reloads faster.", "Wider pools again." },
            "NOTHING. It throws behind the mech, and only checks that something is back there.", new[] { "It is the only weapon in the yard that shoots at where you have BEEN. A fan of acid leaves the mech's back, lands a short way behind, and stays on the ground for a few seconds eating anything that walks through it.", "So it pays you for retreating. Every other gun wants you facing the horde; this one wants you walking away from it, laying ground the crowd has to cross to reach you.", "It will not fire into an empty yard. There has to be something in a wide cone behind you or it holds - which matters, because the magazine is three throws and the reload is long.", "It uses no mount at all, so it fits alongside anything. Nothing else in the game can say that." }),
    };

    public static readonly Ascension[] Ascensions =
    {
        new("w-cannon", "Cannon", "Twin Mount", "The second barrel comes back. Every shot is two shells side by side, aimed together and landing apart - each one hits whatever its own line meets.", "w-twin-mount", "Ordnance"),
        new("w-missile-long", "Long Missiles", "GTM Hornet", "Shortly after launch, every missile still in the air splits into two short-range missiles fifteen degrees apart. The short rack is stripped for parts and its slot comes back empty.", "w-gtm-hornet", "Short Missiles"),
        new("w-laser-short", "Short Laser", "Hydra", "Two more Short Lasers grow from the chassis, at the tier this one reached - three in all. Each picks its own target and runs its own heat, and the mounts they leave standing are still yours to fit another beam to.", "w-hydra", "Servo Drive"),
        new("w-laser-medium", "Medium Laser", "Chain Laser", "The beam jumps. From whatever it burns it reaches the nearest enemy not already in the chain, and keeps going while the whole beam still fits inside its range.", "w-chain-laser", "Targeting Optics"),
        new("w-laser-long", "Long Laser", "Giga Laser", "The beam becomes a channel of red light. It crosses the whole field through bodies, scrap and trees alike, burning everything it covers, aimed where the crowd is thickest - and anything that widens a blast widens it.", "w-giga-laser", "Shaped Charges"),
    };

    /// <summary>Every chassis' one line, which is the mech picker's own.</summary>
    /// <remarks>
    /// THE PICKER'S STRING AND NOT A SECOND ONE. Two descriptions of one chassis is two things
    /// to keep true, and the one nobody is looking at is the one that goes stale. The
    /// consequence is worth knowing: these lines still carry percentages, because a chassis
    /// bonus is not an upgrade card and was not part of stripping the numbers out of the deck.
    /// </remarks>
    public static readonly (string Id, string Name, string Identity)[] Heroes =
    {
        ("slate", "Slate", "Light biped, twin gun pods. Opens with the Medium Laser, and vents its heat 50% faster."),
        ("moss", "Moss", "Light strider, rotary drums. Opens with the Short Laser at double reach."),
        ("ember", "Ember", "Light strider, one heavy cannon. Opens with the Long Laser, 30% hotter-hitting."),
        ("amber", "Amber", "Heavy biped, one heavy cannon. Opens with the Cannon, and its shells punch through."),
        ("onyx", "Onyx", "Heavy quad, boxed missile racks. Opens with the Long Missiles, and fires one more."),
        ("ash", "Ash", "Light biped, boxed missile racks. Opens with the Short Missiles, rearmed 20% faster."),
        ("bone", "Bone", "Light strider, twin gun pods. Opens with the Machine Gun, 30% harder-hitting."),
        ("plum", "Plum", "Heavy biped, no gun at all. Nothing but an Energy Shield, recharging 60% faster. Kill with it."),
        ("fern", "Fern", "Light hover, forward claw arms. Opens with Drones, and builds them 10% faster."),
        ("indigo", "Indigo", "Heavy strider, spine-slung artillery tube. Opens with the Heavy Artillery, blasting 15% wider."),
        ("brass", "Brass", "Light hover, one heavy tube. Opens with the Phase Cannon, 10% harder-hitting."),
        ("vermilion", "Vermilion", "Light hover, rotary drums. Opens with the Flak Cannon, and throws an extra shell every burst."),
        ("jade", "Jade", "Heavy biped, forward claw arms. Opens with Toxic Sludge, laying pools 20% wider."),
        ("rust", "Rust", "Heavy quad, spine-slung artillery tube. Opens with the Mortar, lobbing 30% harder."),
        ("cobalt", "Cobalt", "Heavy quad, twin gun pods. Opens with the Medium Laser."),
        ("copper", "Copper", "Heavy quad, rotary drums. Opens with the Plasma Thrower, throwing 10% further and 10% hotter."),
    };

    /// <summary>A lead paragraph and the notes under it - the shape every bestiary page uses.</summary>
    public readonly record struct Lore(string Key, string Lead, string[] Notes);

    /// <summary>What a variant does, keyed by its own name.</summary>
    public static readonly Lore[] Variants =
    {
        new("plain", "The baseline. Everything else is described against this.", new[] { "No bonus and no weakness. Whatever the wave is made of, this is what it is made of most.", "It is the variant that teaches you the wave: how fast this one walks is how fast you have to walk." }),
        new("swift", "Faster, and paid for in hit points and bite.", new[] { "The one variant that can close a gap you thought you had. It arrives ahead of its own wave and it arrives alone, which is what makes it dangerous - you turn to deal with it and the rest of the crowd is still coming.", "It dies quickly once you are looking at it. The whole threat is where it is, not what it does." }),
        new("tough", "More hit points, less speed, and visibly bigger.", new[] { "Drawn larger than the rest, deliberately: the extra hit points are a fact you have to be able to read at a glance while running.", "It hits no harder than a plain. It just takes longer to stop, which means it is still there while everything behind it catches up." }),
        new("spiky", "Hits much harder than anything else its size.", new[] { "The red rim is the only cue. Its hit points and its speed are ordinary, so nothing about how it moves warns you - and every weapon in the game targets by size or by hit points, so nothing you carry prioritises it either.", "This is the variant that kills a full-health mech by being ignored in a crowd." }),
        new("heavy", "A wall that walks. Ten times the hit points at a twentieth of the speed.", new[] { "It never arrives with the ordinary horde - nothing in the drip can roll one. It comes as a RING ATTACK, a set-piece that drops a circle of them around you and closes it.", "And it barely moves when shot. A shell shoves it a quarter as far as it would shove anything else, so pushing your way out is not the escape it looks like.", "Both halves of the stat line matter. Ten times the hit points alone would be a roadblock you walk around; a twentieth of the speed alone would be a free kill. Together it is a thing you either grind down or go around, and it will still be there when you come back." }),
        new("swarmer", "Twice the speed of anything else, and made of paper.", new[] { "Faster than every mech on the roster. Nothing here can outrun one.", "It arrives as THE SWARM - fifty of them set down off screen in one direction, running at a point near where you were standing rather than at you. So it comes through as a front with gaps in it, and pours past rather than converging.", "Then it turns around and loses half its speed doing it. A thing that fast could never be outrun once it actually started following you, so the trade is fixed: terrifying while it ignores you, ordinary once it does not." }),
        new("chest dropper", "Gold, and worth every second it takes. It leaves a Cyber Chest where it falls.", new[] { "It only ever arrives as a CHEST ELITE - one body, walking in on its own. Nothing in the drip can produce one, and it is the only enemy in the yard you should want to see.", "Three times the hit points of the elite it otherwise is, which on top of the rank is fifteen times a regular. That is the fight: it takes long enough that you have to commit to it while the wave keeps arriving.", "And it is slightly faster than an elite, which is the part that catches people out. Every other big thing in the yard trades speed away for bulk and can be left standing. This one follows.", "It pays half the usual XP. The chest is the payment." }),
    };

    /// <summary>
    /// What a rank means, keyed by its name.
    /// </summary>
    /// <remarks>
    /// ONE COPY FOR ALL OF THEM. A boss means the same thing on both maps and on every rung, and
    /// writing it out per creature is how forty-eight pages start disagreeing with each other.
    /// </remarks>
    public static readonly Lore[] Ranks =
    {
        new("regular", "The horde. What the drip is made of.", new[] { "One rank below elite in every respect, and the only rank that arrives continuously." }),
        new("elite", "Ten times the hit points, half again the damage, and slower.", new[] { "Drops in mid-wave rather than walking on with the crowd, and drawn half again as large.", "Worth eight times the experience of a regular, which is what makes going out of your way for one a real decision rather than an obvious no." }),
        new("boss", "One per wave, and it cannot be pushed.", new[] { "Forty-two times a regular's hit points, more than twice the damage, and a blue outline so it is never lost in a crowd.", "Immovable - its mass is set so high that no weapon in the game moves it at all. Every other body in the yard can be kited by shoving it; this one cannot.", "Sixty times the experience, and it drops a Cyber Chest." }),
    };

    /// <summary>A ladder rung's character, keyed <c>levelId/cycleName</c>.</summary>
    /// <remarks>
    /// THE LEVEL ID IS PART OF THE KEY, for the same reason it is part of the save key: two maps
    /// may one day name a rung the same thing, and a Mossy page appearing on a Scrapyard creature
    /// is exactly the confusion the per-level content split exists to prevent.
    /// </remarks>
    public static readonly Lore[] Cycles =
    {
        new("scrapyard/Rustling", "The first thing that ever came for you, and the slowest.", new[] { "It arrives alone, in ones and twos, and it dies to whatever you are holding. That is the point: the opening minutes are where you find out what your guns do without anything punishing you for looking.", "Nothing else in the yard is this forgiving. If a Rustling reaches you, you were standing still." }),
        new("scrapyard/Scavenger", "Quicker than a Rustling and no tougher at all.", new[] { "The wave that teaches you distance is not safety. It closes gaps you had already decided were enough, and it does it while you are looking at something else.", "It still dies immediately. The whole threat is where it is, not what it does when it gets there." }),
        new("scrapyard/Hauler", "Slow and fat. You can walk away from these; you cannot ignore them.", new[] { "The first body that outlives your attention. It takes long enough to bring down that the wave behind it arrives while you are still working, which is a different problem from anything before it.", "Nothing about it is fast. Everything about it is in the way." }),
        new("scrapyard/Prowler", "The fastest thing in the yard, and lighter than what came before it.", new[] { "The one rung where the horde gets FLIMSIER than the last. It is a change of question rather than an increase: the Hauler asked how long you could keep firing, this asks whether you can be somewhere else.", "It will catch you if you commit to a fight facing the wrong way." }),
        new("scrapyard/Hardhead", "Slams the brakes, and nearly doubles the bite.", new[] { "The first cycle that genuinely hurts to touch. Everything before it could be walked through in an emergency; this is where that stops being free.", "Wide, and it does not move when you shoot it. Slow enough that none of that has to happen to you - being hit by one is a decision you made a second earlier." }),
        new("scrapyard/Breaker", "Quick again, and it hits harder than anything so far.", new[] { "The Hardhead was slow enough to forgive a mistake. This is not, and it arrives with the pace of the Prowler and the weight of the Hardhead at the same time.", "The rung where standing your ground stops being a style and starts being a way to die." }),
        new("scrapyard/Warden", "Tanky and unhurried.", new[] { "It does not chase and it does not need to. By this point in a run the field never empties, so a body that simply refuses to fall is doing the work of three that would have.", "Bites less than the Breaker did. It is a wall being built around you rather than a thing attacking you." }),
        new("scrapyard/Dozer", "The slowest thing in the yard, and the hardest to finish.", new[] { "The endgame is NUMBERS, not pace. It closes in slowly and the problem is that there is no gap in it.", "Lighter than it looks for something that takes this long to kill - it can be shoved, and late on that is the difference between a corner you chose and one you were pushed into." }),
        new("mossy-mayhem/Sporeling", "Slow, soft, and there are a great many of them.", new[] { "Moss opens the way the yard does - with something that cannot hurt you while you work out what your guns do on new ground.", "The same creature stands in for all three ranks here. What changes is how big it is and how long it takes." }),
        new("mossy-mayhem/Swarm", "Fast and flimsy. Distance is not safety out here either.", new[] { "It escalates by getting more weapon rather than more body: a blowfly, then a killer bee, then a mosquito the size of the bee. You can read which one is coming before it arrives.", "None of the three survives being looked at. All of them are somewhere you did not expect." }),
        new("mossy-mayhem/Formless", "Slow and fat. Walk away from these; do not ignore them.", new[] { "A jelly, then an ooze, then something with a shell on.", "HURT THE BIG ONE ENOUGH AND ITS SHELL COMES OFF. What is left is faster to look at and no easier to finish - the shell was never the fight, it was the half of the fight you had done." }),
        new("mossy-mayhem/Pack", "The fastest thing on the moss, and lighter than the Formless before it.", new[] { "A jackal, then something with lightning in it, then something on fire. Three dogs, and the escalation is what they are made of rather than how big they are.", "The rung that punishes committing to a direction." }),
        new("mossy-mayhem/Vine Stalker", "Slams the brakes, and nearly doubles the bite.", new[] { "The first thing on this map that hurts to touch. It does not chase well and it does not have to.", "Rooted-looking and absolutely not rooted. That is the joke and it costs you the first time." }),
        new("mossy-mayhem/Draconian", "Quick again, and it hits hardest of anything so far.", new[] { "Pace and weight arriving together, which is the combination the Vine Stalker let you off.", "The rung where the moss stops being the easier map." }),
        new("mossy-mayhem/Golem", "Tanky and unhurried - dirt, then rock, then metal.", new[] { "The three ranks are three materials, and you can tell at a glance which one you have walked into.", "It bites less than the Draconian did. It simply does not fall over, and by now the field never empties." }),
        new("mossy-mayhem/Wyrm", "A wall. The slowest thing on the map and by far the heaviest.", new[] { "A dragon, then a golden one, then something with rather more heads than that.", "THE BIG ONE LOSES A HEAD EVERY TIME YOU TAKE A FIFTH OF IT DOWN. It is the only health bar in the game you can read from across the field without looking at the bar." }),
        new("city-chaos/Junkbots", "The first machine this street sends, and there is only ever one of it at a time.", new[] { "It wanders more than it hunts, and for the first two minutes on this map that is the whole horde - the same courtesy the Scrapyard opened with, so what you learn first here is the grid, not your own guns again.", "ITS BOSS DOES NOT STAY DOWN. Beat it here, alone, and it is back next cycle walking in pairs beside something new - the promotion is what this map is built around, and it starts on the very first rung." }),
        new("city-chaos/Sentries", "Unarmed, and faster for it. A security bot that runs rather than fights.", new[] { "It carries nothing that can hurt you, so the only cost it charges is your attention - every one that slips past is one you chose not to shoot rather than one that beat you.", "The elite here is a face already put down once: the boss from last cycle, walking again at the same size it fell at." }),
        new("city-chaos/Drones", "The fastest thing this street fields, and it comes from above.", new[] { "Nothing on the ground outruns one. What saves you is that it is as fragile as everything else this early - the danger is entirely in how many of them are suddenly in the air at once.", "The boss from last cycle is promoted into the elite slot again here, still built the same size it went down at." }),
        new("city-chaos/Rovers", "Six wheels, no hurry, and no reason to be anywhere but where you already are.", new[] { "The first body on this map that outlasts your attention. It is not fast enough to catch you and does not need to be - the wave behind it is what you are actually racing.", "The body class steps up here, so the elite beside it is not the old boss shrunk down to fit - it is the same machine, built up to full weight for the rung it now stands on." }),
        new("city-chaos/Gun Sentries", "The sentry from three streets back, and now it is armed.", new[] { "Slams the brakes and very nearly doubles the bite - the first machine on this map you cannot walk through by accident and shrug off.", "It does not chase well. Being hit by one this early is a decision made a second before it happened, not something done to you." }),
        new("city-chaos/Gun Drones", "The drone from two cycles back, armed and quick again.", new[] { "Pace and payload arrive together this time, which is the combination the Gun Sentries let you off - it hits harder than anything so far and is fast enough to reach you doing it.", "The rung where standing under an empty sky stops being safe by default." }),
        new("city-chaos/Fighters", "Strafing aircraft, and unhurried about it.", new[] { "It does not need to close in - it already owns the air above you, and by this point in a run the sky is never empty either.", "Bites less than the Gun Drones did. It wears you down over a pass rather than threatening you with one." }),
        new("city-chaos/Armour", "A wall of dozer-yellow tanks, and the slowest thing this street fields.", new[] { "The endgame here is the same as everywhere else: numbers, not pace. It closes in slowly and there is no gap anywhere in the column behind it.", "The last promotion on the ladder: the boss from two cycles back is built up to full weight now, standing beside armour that never learned to hurry." }),
    };

    public static Lore? LoreIn(Lore[] table, string key)
    {
        foreach (var l in table) if (l.Key == key) return l;
        return null;
    }

    public static Entry? Find(string id)
    {
        foreach (var e in All) if (e.Id == id) return e;
        return null;
    }

    public static Ascension? AscensionOf(string parentId)
    {
        foreach (var a in Ascensions) if (a.ParentId == parentId) return a;
        return null;
    }

    /// <summary>The catalogs' fingerprint when this file was emitted. See the tests.</summary>
    public const uint CatalogDigest = 0xd5dbef74u;
}
