// <auto-generated />
// Generated by tools/gen_sfx_table.ts - `npm run sfxtable`. DO NOT EDIT BY HAND.
//
// The mix lives in src/render/audio/sfxCatalog.ts and sfxTriggers.ts, which are the one
// authored copy for both front-ends. Nothing about sound is in the world hash, so a value
// mistyped here would change how the desktop build sounds and fail no test anywhere - which
// is exactly why this file is emitted rather than transcribed. See the generator's header.

namespace Scrapyard.Game;

/// <summary>Which mixer group a sound belongs to. One volume per bus, never one per clip.</summary>
public enum SfxBus
{
    Weapon,
    Impact,
    Pickup,
    Ui,
    Body,
    World,
}

/// <summary>Every sound the game is allowed to make. 48 of them.</summary>
public enum SfxId
{
    FireCannon,
    FireMg,
    FireFlak,
    FireMortar,
    FireArtillery,
    FireMissileS,
    FireMissileL,
    FireLaserS,
    FireLaserM,
    FireLaserL,
    FirePhase,
    FirePlasma,
    FireSludge,
    FireDrone,
    HitBullet,
    HitLaser,
    HitPlasma,
    BlastSmall,
    BlastMedium,
    BlastLarge,
    SplatAcid,
    PickGem,
    PickCredit,
    PickRepair,
    PickMagnet,
    PickDice,
    PickSheep,
    LevelUp,
    CardTaken,
    ChestOpen,
    Ascend,
    Achievement,
    DieGrunt,
    DieElite,
    PlayerHurt,
    ShieldBreak,
    BossWarn,
    DieBoss,
    EventSwarm,
    RunLost,
    RunWon,
    BarrelBreak,
    WallBreak,
    Reload,
    Overheat,
    UiMove,
    UiConfirm,
    UiDeny,
}

/// <summary>One row of the library. See <c>sfxCatalog.ts</c> for what each column means.</summary>
/// <param name="Clip">Resolves to <c>cs/assets/sfx/&lt;clip&gt;.wav</c>.</param>
/// <param name="ThrottleMs">The floor between two plays. 0 means "cannot double up".</param>
/// <param name="Gain">Baseline gain before the bus fader. A gem is never as loud as a boss.</param>
/// <param name="Loop">True for the beams, which run until told to stop rather than firing once.</param>
public readonly record struct SfxDef(
    SfxId Id, string Clip, SfxBus Bus, int ThrottleMs, float Gain, bool Loop, string Brief);

public static class SfxTable
{
    /// <summary>The library, in the order the brief lays it out.</summary>
    public static readonly SfxDef[] All =
    [
        new(SfxId.FireCannon, "fire_cannon", SfxBus.Weapon, 110, 0.55f, false, "One heavy shell, about one a second"),
        new(SfxId.FireMg, "fire_mg", SfxBus.Weapon, 60, 0.3f, false, "A two-round burst, 11 times a second"),
        new(SfxId.FireFlak, "fire_flak", SfxBus.Weapon, 70, 0.4f, false, "Four shells into a wide cone"),
        new(SfxId.FireMortar, "fire_mortar", SfxBus.Weapon, 140, 0.55f, false, "One shell lobbed high, every two seconds"),
        new(SfxId.FireArtillery, "fire_artillery", SfxBus.Weapon, 200, 0.7f, false, "Two shells called down from off-map"),
        new(SfxId.FireMissileS, "fire_missile_s", SfxBus.Weapon, 90, 0.45f, false, "Two tubes, every three seconds"),
        new(SfxId.FireMissileL, "fire_missile_l", SfxBus.Weapon, 120, 0.5f, false, "Five tubes, every four seconds"),
        new(SfxId.FireLaserS, "fire_laser_s", SfxBus.Weapon, 0, 0.3f, true, "A continuous beam - seamless loop"),
        new(SfxId.FireLaserM, "fire_laser_m", SfxBus.Weapon, 0, 0.34f, true, "A continuous beam - seamless loop"),
        new(SfxId.FireLaserL, "fire_laser_l", SfxBus.Weapon, 0, 0.38f, true, "A continuous beam - seamless loop"),
        new(SfxId.FirePhase, "fire_phase", SfxBus.Weapon, 100, 0.5f, false, "A slow energy bolt, every 1.6s"),
        new(SfxId.FirePlasma, "fire_plasma", SfxBus.Weapon, 70, 0.3f, false, "A stream of bolts, four a second"),
        new(SfxId.FireSludge, "fire_sludge", SfxBus.Weapon, 100, 0.42f, false, "A lobbed canister, every 1.5s"),
        new(SfxId.FireDrone, "fire_drone", SfxBus.Weapon, 120, 0.22f, false, "A drone released from the bay"),
        new(SfxId.HitBullet, "hit_bullet", SfxBus.Impact, 45, 0.28f, false, "Cannon, machine gun, flak, on a body"),
        new(SfxId.HitLaser, "hit_laser", SfxBus.Impact, 45, 0.26f, false, "Any beam, and the Phase Cannon"),
        new(SfxId.HitPlasma, "hit_plasma", SfxBus.Impact, 50, 0.28f, false, "Plasma bolts, and anything that sets a burn"),
        new(SfxId.BlastSmall, "blast_small", SfxBus.Impact, 70, 0.45f, false, "Flak shells, short missiles, a drone dying"),
        new(SfxId.BlastMedium, "blast_medium", SfxBus.Impact, 80, 0.6f, false, "Phase Cannon, mortar shells"),
        new(SfxId.BlastLarge, "blast_large", SfxBus.Impact, 120, 0.85f, false, "Artillery, long missiles"),
        new(SfxId.SplatAcid, "splat_acid", SfxBus.Impact, 90, 0.4f, false, "A sludge canister bursting into a puddle"),
        new(SfxId.PickGem, "pick_gem", SfxBus.Pickup, 40, 0.18f, false, "Every gem collected - the most frequent sound in the game"),
        new(SfxId.PickCredit, "pick_credit", SfxBus.Pickup, 70, 0.28f, false, "A blue coin walked over"),
        new(SfxId.PickRepair, "pick_repair", SfxBus.Pickup, 120, 0.45f, false, "A repair pickup, hull restored"),
        new(SfxId.PickMagnet, "pick_magnet", SfxBus.Pickup, 150, 0.5f, false, "The magnet powerup starting its sweep"),
        new(SfxId.PickDice, "pick_dice", SfxBus.Pickup, 150, 0.45f, false, "The reroll die, once a run"),
        new(SfxId.PickSheep, "pick_sheep", SfxBus.Pickup, 120, 0.4f, false, "Mossy Mayhem’s loot prop, caught"),
        new(SfxId.LevelUp, "level_up", SfxBus.Pickup, 0, 0.65f, false, "A level gained, the card about to open"),
        new(SfxId.CardTaken, "card_taken", SfxBus.Ui, 0, 0.55f, false, "A card chosen from the level-up screen"),
        new(SfxId.ChestOpen, "chest_open", SfxBus.Pickup, 0, 0.75f, false, "A chest opening - the run stops for it"),
        new(SfxId.Ascend, "ascend", SfxBus.Pickup, 0, 0.8f, false, "A weapon reaching tier 8 - the one secret in the game"),
        new(SfxId.Achievement, "achievement", SfxBus.Ui, 0, 0.55f, false, "An achievement unlocking, over whatever is happening"),
        new(SfxId.DieGrunt, "die_grunt", SfxBus.Body, 80, 0.26f, false, "Any regular enemy dying - plays constantly"),
        new(SfxId.DieElite, "die_elite", SfxBus.Body, 120, 0.45f, false, "An elite dying"),
        new(SfxId.PlayerHurt, "player_hurt", SfxBus.Body, 150, 0.6f, false, "The mech taking damage"),
        new(SfxId.ShieldBreak, "shield_break", SfxBus.Body, 100, 0.55f, false, "An energy shield rim going down"),
        new(SfxId.BossWarn, "boss_warn", SfxBus.Body, 0, 0.85f, false, "The cycle boss walking in"),
        new(SfxId.DieBoss, "die_boss", SfxBus.Body, 0, 0.85f, false, "A boss going down"),
        new(SfxId.EventSwarm, "event_swarm", SfxBus.World, 0, 0.6f, false, "The swarm set-piece starting"),
        new(SfxId.RunLost, "run_lost", SfxBus.Body, 0, 1f, false, "The run ending in failure"),
        new(SfxId.RunWon, "run_won", SfxBus.Body, 0, 1f, false, "Surviving the clock with every boss down"),
        new(SfxId.BarrelBreak, "barrel_break", SfxBus.World, 90, 0.42f, false, "A drum shot open"),
        new(SfxId.WallBreak, "wall_break", SfxBus.World, 90, 0.38f, false, "A tree felled, a site fence opened"),
        new(SfxId.Reload, "reload", SfxBus.Weapon, 200, 0.38f, false, "A magazine weapon coming back online"),
        new(SfxId.Overheat, "overheat", SfxBus.Weapon, 200, 0.5f, false, "A beam weapon cutting out"),
        new(SfxId.UiMove, "ui_move", SfxBus.Ui, 30, 0.22f, false, "Cursor moving between options"),
        new(SfxId.UiConfirm, "ui_confirm", SfxBus.Ui, 40, 0.38f, false, "An option chosen"),
        new(SfxId.UiDeny, "ui_deny", SfxBus.Ui, 60, 0.38f, false, "Something unaffordable or locked"),
    ];

    /// <summary>
    /// ONE SOUND PER EVENT KIND, indexed by the kind itself, or null for the majority that are
    /// a visual fact only. Routed kinds carry a FALLBACK rather than null, so a router that is
    /// ever missed still makes the right KIND of noise - see <c>Sfx.PlayFor</c>.
    /// </summary>
    public static readonly SfxId?[] ByEvent =
    [
        null,                         // 0 EnemySpawned
        null,                         // 1 EnemyDamaged
        SfxId.DieGrunt,               // 2 EnemyKilled
        SfxId.PlayerHurt,             // 3 PlayerDamaged
        null,                         // 4 WeaponFired
        SfxId.HitBullet,              // 5 ProjectileHit
        null,                         // 6 ProjectileExpired
        null,                         // 7 GemSpawned
        SfxId.PickGem,                // 8 GemCollected
        SfxId.LevelUp,                // 9 LevelUp
        SfxId.CardTaken,              // 10 UpgradeTaken
        null,                         // 11 PhaseChanged
        SfxId.BossWarn,               // 12 BossSpawned
        SfxId.Overheat,               // 13 WeaponOverheated
        null,                         // 14 WeaponCooled
        null,                         // 15 WeaponReloading
        SfxId.Reload,                 // 16 WeaponReloaded
        SfxId.ShieldBreak,            // 17 PlayerShieldBroken
        null,                         // 18 PlayerShieldRestored
        SfxId.BlastMedium,            // 19 ProjectileDetonated
        SfxId.BarrelBreak,            // 20 BarrelBroken
        SfxId.PickCredit,             // 21 ConsumableTaken
        SfxId.ChestOpen,              // 22 ChestOpened
        null,                         // 23 ChestClosed
        null,                         // 24 BarrelGrew
        null,                         // 25 UpgradeRerolled
        null,                         // 26 SpecialEvent
        null,                         // 27 PlayerRepaired
        SfxId.PickRepair,             // 28 PlayerSaved
        SfxId.WallBreak,              // 29 WallBroken
        SfxId.FireDrone,              // 30 DroneFired
        SfxId.PickSheep,              // 31 SheepTaken
    ];

    /// <summary>
    /// WHAT EACH GUN SOUNDS LIKE, indexed by weapon def id. Fourteen weapons, fourteen clips,
    /// and no sharing. The three beams name their LOOP, which is what <c>Sfx.FireSfxFor</c>
    /// turns into silence when a one-shot would otherwise be fired.
    /// </summary>
    public static readonly SfxId[] FireByWeapon =
    [
        SfxId.FireCannon,             // 0 cannon
        SfxId.FireLaserS,             // 1 laser-short
        SfxId.FireLaserM,             // 2 laser-medium
        SfxId.FireLaserL,             // 3 laser-long
        SfxId.FireMissileS,           // 4 missile-short
        SfxId.FireMissileL,           // 5 missile-long
        SfxId.FireMg,                 // 6 machine-gun
        SfxId.FireFlak,               // 7 flak-cannon
        SfxId.FireArtillery,          // 8 artillery
        SfxId.FireDrone,              // 9 drone
        SfxId.FirePhase,              // 10 phase-cannon
        SfxId.FireMortar,             // 11 mortar
        SfxId.FirePlasma,             // 12 plasma
        SfxId.FireSludge,             // 13 sludge
    ];

    /// <summary>Blast grades, by radius. See <c>sfxTriggers.ts</c> for why these boundaries.</summary>
    public const double BlastSmallMax = 40;
    public const double BlastMediumMax = 110;
}
